-- RASCUNHO NÃO VERIFICADO. Todas as ~140 linhas abaixo foram escritas de memória, sem pesquisa
-- (sem WebSearch/WebFetch) — é geração de volume de candidatos, não curadoria. Todo `answer` é
-- estimativa educada; toda `source_name`/`source_url` é placeholder. status = 'pending' em toda
-- linha; start_round só sorteia status = 'approved', então nada aqui entra em partida real antes
-- de uma sessão futura confirmar cada número com fonte real e decidir aprovar/rejeitar (mesmo
-- processo usado no início do banco, ver cabeçalho de futebol_01.sql).
--
-- Foco: ligas domésticas, clubes e seleções da AMÉRICA DO SUL fora do Brasil — Argentina,
-- Uruguai, Chile, Colômbia, Peru, Paraguai, Equador, Venezuela, Bolívia.
--
-- Famílias incluídas (cada uma cobre 1 métrica, variando o clube/país/jogador):
--   1.  Artilheiro histórico do clube (maior goleador de sempre) — por clube sul-americano
--   2.  Clube com mais títulos da liga nacional — por país
--   3.  Ano de fundação do clube — clubes tradicionais
--   4.  Capacidade do estádio do clube
--   5.  Clássico mais tradicional do país (ano da primeira edição)
--   6.  Jogador com mais jogos pela seleção nacional (recordista de partidas)
--   7.  Maior artilheiro histórico da seleção nacional
--   8.  Participações em Copas do Mundo por seleção
--   9.  Clube com mais títulos da Libertadores, por país
--   10. Recorde de invencibilidade numa liga nacional (jogos seguidos sem perder)
--   11. Maior goleada da história do clube num campeonato nacional
--   12. Transferência de saída mais cara da história do clube
--   13. Público recorde do estádio do clube (maior comparecimento já registrado)
--   14. Ano do último título de liga do clube (jejum de clube tradicional)

insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values

-- Família 1: artilheiro histórico do clube (maior goleador de sempre)
  ('Ángel Labruna é o maior ídolo histórico do River Plate, na Argentina. Quantos gols ele marcou pelo clube ao longo da carreira?',
   317, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1959, 'pending'),
  ('Martín Palermo é o maior artilheiro da história do Boca Juniors. Quantos gols ele marcou pelo clube?',
   236, 'gols', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2011, 'pending'),
  ('Arsenio Erico, paraguaio que virou lenda na Argentina, é o maior artilheiro histórico do Independiente. Quantos gols ele marcou pelo clube?',
   293, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1939, 'pending'),
  ('Fernando Morena é o maior artilheiro da história do Peñarol, no Uruguai. Quantos gols ele marcou pelo clube?',
   230, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1983, 'pending'),
  ('Atilio García é o maior artilheiro da história do Nacional, do Uruguai. Quantos gols ele marcou pelo clube?',
   208, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1949, 'pending'),
  ('Esteban Paredes é o maior artilheiro da história do Colo-Colo, no Chile. Quantos gols ele marcou pelo clube?',
   223, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Carlos Campos é um dos maiores artilheiros da história da Universidad de Chile. Quantos gols ele marcou pelo clube na carreira?',
   174, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1970, 'pending'),
  ('Alfonso Cañón é um dos maiores artilheiros da história do Millonarios, na Colômbia. Quantos gols ele marcou pelo clube?',
   149, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1971, 'pending'),
  ('Teófilo Cubillas, um dos maiores jogadores da história do Peru, é ídolo do Alianza Lima. Quantos gols ele marcou pelo clube?',
   130, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1973, 'pending'),
  ('Delfín Benítez Cáceres é um dos maiores artilheiros da história do Olimpia, no Paraguai. Quantos gols ele marcou pelo clube?',
   209, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1943, 'pending'),

-- Família 2: clube com mais títulos da liga nacional, por país
  ('Na Argentina, o River Plate é um dos clubes mais titulados da liga nacional. Quantos títulos de primeira divisão ele já venceu, ao todo?',
   38, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('No Uruguai, o Peñarol é o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   54, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('No Chile, o Colo-Colo é o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   34, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Na Colômbia, o Atlético Nacional é um dos maiores campeões da liga nacional. Quantos títulos ele já venceu, ao todo?',
   18, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('No Peru, o Universitario de Deportes é o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   26, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('No Paraguai, o Olimpia é disparado o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   46, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('No Equador, o Barcelona SC é um dos maiores campeões da liga nacional. Quantos títulos ele já venceu, ao todo?',
   17, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Na Venezuela, o Caracas FC é um dos maiores campeões da liga nacional. Quantos títulos ele já venceu, ao todo?',
   13, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Na Bolívia, o Bolívar é um dos maiores campeões da liga nacional. Quantos títulos ele já venceu, ao todo?',
   22, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Na Argentina, o Boca Juniors é o segundo maior campeão da liga nacional, atrás só do River Plate. Quantos títulos ele já venceu, ao todo?',
   35, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),

-- Família 3: ano de fundação do clube
  ('Em que ano foi fundado o River Plate, um dos clubes mais tradicionais da Argentina?',
   1901, 'ano', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1901, 'pending'),
  ('Em que ano foi fundado o Boca Juniors, um dos clubes mais populares da Argentina?',
   1905, 'ano', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1905, 'pending'),
  ('Em que ano foi fundado o Peñarol, um dos clubes mais tradicionais do Uruguai?',
   1891, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1891, 'pending'),
  ('Em que ano foi fundado o Nacional, um dos clubes mais tradicionais do Uruguai?',
   1899, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1899, 'pending'),
  ('Em que ano foi fundado o Colo-Colo, o clube mais popular do Chile?',
   1925, 'ano', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1925, 'pending'),
  ('Em que ano foi fundada a Universidad de Chile, um dos clubes mais tradicionais do Chile?',
   1927, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1927, 'pending'),
  ('Em que ano foi fundado o Atlético Nacional, um dos maiores clubes da Colômbia?',
   1947, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1947, 'pending'),
  ('Em que ano foi fundado o Barcelona SC, o clube mais popular do Equador?',
   1925, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1925, 'pending'),
  ('Em que ano foi fundado o Bolívar, um dos maiores clubes da Bolívia?',
   1925, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1925, 'pending'),
  ('Em que ano foi fundado o Olimpia, o clube mais tradicional do Paraguai?',
   1902, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1902, 'pending'),

-- Família 4: capacidade do estádio do clube
  ('Qual a capacidade do Estádio Monumental, casa do River Plate, na Argentina?',
   83000, 'lugares', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade da Bombonera, estádio do Boca Juniors, na Argentina?',
   54000, 'lugares', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Centenário, em Montevidéu, palco da primeira Copa do Mundo?',
   60000, 'lugares', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Campeón del Siglo, casa do Peñarol, no Uruguai?',
   40000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Monumental David Arellano, casa do Colo-Colo, no Chile?',
   47000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Nacional do Chile, em Santiago, casa da seleção chilena?',
   48000, 'lugares', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio El Campín, em Bogotá, na Colômbia?',
   36000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Atanasio Girardot, em Medellín, casa do Atlético Nacional?',
   40000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Monumental Banco Pichincha, casa do Barcelona SC, no Equador?',
   57000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Hernando Siles, em La Paz, casa da seleção boliviana?',
   41000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

-- Família 5: clássico mais tradicional do país (ano da primeira edição)
  ('O Superclássico entre River Plate e Boca Juniors é um dos maiores do mundo. Em que ano foi disputada a primeira edição?',
   1913, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1913, 'pending'),
  ('O clássico entre Peñarol e Nacional é o mais tradicional do futebol uruguaio. Em que ano foi disputada a primeira edição?',
   1900, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1900, 'pending'),
  ('O Superclássico chileno, entre Colo-Colo e Universidad de Chile, é o maior do país. Em que ano foi disputada a primeira edição?',
   1937, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1937, 'pending'),
  ('O clássico bogotano entre Millonarios e Independiente Santa Fe é o mais tradicional da Colômbia. Em que ano foi disputada a primeira edição?',
   1948, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1948, 'pending'),
  ('O clássico entre Alianza Lima e Universitario de Deportes é o mais tradicional do Peru. Em que ano foi disputada a primeira edição?',
   1928, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1928, 'pending'),
  ('O clássico paraguaio entre Olimpia e Cerro Porteño é o mais tradicional do país. Em que ano foi disputada a primeira edição?',
   1912, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1912, 'pending'),
  ('O Clássico do Astillero, entre Barcelona SC e Emelec, é o mais tradicional do Equador. Em que ano foi disputada a primeira edição?',
   1930, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1930, 'pending'),
  ('O clássico paceño, entre Bolívar e The Strongest, é o mais tradicional da Bolívia. Em que ano foi disputada a primeira edição?',
   1930, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1930, 'pending'),
  ('O clássico caraquenho, entre Caracas FC e Deportivo Táchira, é um dos mais acompanhados da Venezuela. Em que ano foi disputada a primeira edição?',
   1974, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1974, 'pending'),
  ('O clássico rosarino, entre Newell''s Old Boys e Rosario Central, é um dos mais intensos da Argentina. Em que ano foi disputada a primeira edição?',
   1905, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1905, 'pending'),

-- Família 6: jogador com mais jogos pela seleção nacional (recordista de partidas)
  ('Lionel Messi se tornou o jogador com mais partidas pela seleção argentina. Quantos jogos ele já disputou pela Argentina?',
   190, 'jogos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Diego Godín é o jogador com mais partidas pela seleção uruguaia. Quantos jogos ele disputou pelo Uruguai?',
   167, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Claudio Bravo é um dos jogadores com mais partidas pela seleção chilena. Quantos jogos ele disputou pelo Chile?',
   148, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('David Ospina é um dos jogadores com mais partidas pela seleção colombiana. Quantos jogos ele disputou pela Colômbia?',
   130, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Roberto Palacios é o jogador com mais partidas pela seleção peruana. Quantos jogos ele disputou pelo Peru?',
   148, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2007, 'pending'),
  ('Paulo da Silva é o jogador com mais partidas pela seleção paraguaia. Quantos jogos ele disputou pelo Paraguai?',
   146, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Iván Hurtado é o jogador com mais partidas pela seleção equatoriana. Quantos jogos ele disputou pelo Equador?',
   168, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2012, 'pending'),
  ('Juan Arango é um dos jogadores com mais partidas pela seleção venezuelana. Quantos jogos ele disputou pela Venezuela?',
   129, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2016, 'pending'),
  ('Ronald Raldes é um dos jogadores com mais partidas pela seleção boliviana. Quantos jogos ele disputou pela Bolívia?',
   100, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Antes de Messi, Javier Mascherano era o recordista de partidas pela seleção argentina. Quantos jogos ele disputou pela Argentina?',
   147, 'jogos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2018, 'pending'),

-- Família 7: maior artilheiro histórico da seleção nacional
  ('Lionel Messi é o maior artilheiro da história da seleção argentina. Quantos gols ele já marcou pela Argentina?',
   109, 'gols', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Luis Suárez é o maior artilheiro da história da seleção uruguaia. Quantos gols ele marcou pelo Uruguai?',
   69, 'gols', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Alexis Sánchez é o maior artilheiro da história da seleção chilena. Quantos gols ele marcou pelo Chile?',
   50, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Radamel Falcao é o maior artilheiro da história da seleção colombiana. Quantos gols ele marcou pela Colômbia?',
   36, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Paolo Guerrero é o maior artilheiro da história da seleção peruana. Quantos gols ele marcou pelo Peru?',
   39, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Roque Santa Cruz é o maior artilheiro da história da seleção paraguaia. Quantos gols ele marcou pelo Paraguai?',
   32, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Enner Valencia é o maior artilheiro da história da seleção equatoriana. Quantos gols ele marcou pelo Equador?',
   46, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Salomón Rondón é o maior artilheiro da história da seleção venezuelana. Quantos gols ele marcou pela Venezuela?',
   40, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Joaquín Botero é um dos maiores artilheiros da história da seleção boliviana. Quantos gols ele marcou pela Bolívia?',
   20, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2007, 'pending'),
  ('Edinson Cavani é o segundo maior artilheiro da história da seleção uruguaia, atrás só de Luis Suárez. Quantos gols ele marcou pelo Uruguai?',
   58, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

-- Família 8: participações em Copas do Mundo por seleção
  ('Quantas Copas do Mundo a Argentina já disputou, ao todo, contando até a edição de 2022?',
   18, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo o Uruguai já disputou, ao todo, sendo um dos países com mais participações?',
   14, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo o Chile já disputou, ao todo, contando até a edição de 2022?',
   9, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo a Colômbia já disputou, ao todo, contando até a edição de 2022?',
   6, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo o Peru já disputou, ao todo, contando até a edição de 2018?',
   5, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2018, 'pending'),
  ('Quantas Copas do Mundo o Paraguai já disputou, ao todo, contando até a edição de 2010?',
   8, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('Quantas Copas do Mundo o Equador já disputou, ao todo, contando até a edição de 2022?',
   4, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('A Venezuela é a única seleção sul-americana a nunca ter se classificado para uma Copa do Mundo. Quantas participações ela tem, ao todo?',
   0, 'participações', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Quantas Copas do Mundo a Bolívia já disputou, ao todo, contando até a edição de 1994?',
   3, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1994, 'pending'),
  ('A Colômbia ficou de fora de três Copas do Mundo seguidas depois de 1998. Quantas edições seguidas ela ficou sem se classificar, antes de voltar em 2014?',
   3, 'edições', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),

-- Família 9: clube com mais títulos da Libertadores, por país
  ('O Independiente, da Argentina, é o clube mais titulado da história da Copa Libertadores. Quantos títulos ele já venceu?',
   7, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1995, 'pending'),
  ('O Peñarol, do Uruguai, é um dos clubes mais titulados da história da Libertadores. Quantos títulos ele já venceu?',
   5, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1987, 'pending'),
  ('O Olimpia, do Paraguai, é o clube paraguaio mais titulado da Libertadores. Quantos títulos ele já venceu?',
   3, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2002, 'pending'),
  ('O Atlético Nacional é o clube colombiano mais titulado da Libertadores. Quantos títulos ele já venceu?',
   2, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2016, 'pending'),
  ('O Colo-Colo é o único clube chileno a já ter vencido a Libertadores. Quantas vezes ele conquistou o título?',
   1, 'título', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1991, 'pending'),
  ('A LDU de Quito é o único clube equatoriano a já ter vencido a Libertadores. Quantas vezes ela conquistou o título?',
   1, 'título', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2008, 'pending'),
  ('Nenhum clube peruano jamais venceu a Copa Libertadores. Quantas vezes um clube do Peru chegou a ser campeão da competição?',
   0, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Nenhum clube venezuelano jamais venceu a Copa Libertadores. Quantas vezes um clube da Venezuela chegou a ser campeão da competição?',
   0, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Nenhum clube boliviano jamais venceu a Copa Libertadores. Quantas vezes um clube da Bolívia chegou a ser campeão da competição?',
   0, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Boca Juniors é o segundo clube mais titulado da história da Libertadores, atrás só do Independiente. Quantos títulos ele já venceu?',
   6, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2007, 'pending'),

-- Família 10: recorde de invencibilidade numa liga nacional (jogos seguidos sem perder)
  ('O River Plate teve uma sequência marcante de invencibilidade na liga argentina. Qual o recorde de jogos seguidos sem perder do clube?',
   32, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2008, 'pending'),
  ('O Boca Juniors teve uma sequência marcante de invencibilidade na liga argentina. Qual o recorde de jogos seguidos sem perder do clube?',
   40, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1998, 'pending'),
  ('O Peñarol teve uma longa sequência invicta na liga uruguaia. Qual o recorde de jogos seguidos sem perder do clube?',
   40, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2013, 'pending'),
  ('O Colo-Colo teve uma sequência marcante de invencibilidade na liga chilena. Qual o recorde de jogos seguidos sem perder do clube?',
   33, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2007, 'pending'),
  ('O Millonarios teve uma sequência marcante de invencibilidade na liga colombiana. Qual o recorde de jogos seguidos sem perder do clube?',
   26, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2012, 'pending'),
  ('O Universitario de Deportes teve uma sequência marcante de invencibilidade na liga peruana. Qual o recorde de jogos seguidos sem perder do clube?',
   30, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2009, 'pending'),
  ('O Olimpia teve uma sequência marcante de invencibilidade na liga paraguaia. Qual o recorde de jogos seguidos sem perder do clube?',
   31, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2011, 'pending'),
  ('A LDU de Quito teve uma sequência marcante de invencibilidade na liga equatoriana. Qual o recorde de jogos seguidos sem perder do clube?',
   24, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('O Deportivo Táchira teve uma sequência marcante de invencibilidade na liga venezuelana. Qual o recorde de jogos seguidos sem perder do clube?',
   22, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('O Bolívar teve uma sequência marcante de invencibilidade na liga boliviana. Qual o recorde de jogos seguidos sem perder do clube?',
   28, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),

-- Família 11: maior goleada da história do clube num campeonato nacional
  ('Qual a maior goleada da história do River Plate num jogo da liga argentina?',
   8, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1975, 'pending'),
  ('Qual a maior goleada da história do Boca Juniors num jogo da liga argentina?',
   8, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1940, 'pending'),
  ('Qual a maior goleada da história do Peñarol num jogo da liga uruguaia?',
   9, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1950, 'pending'),
  ('Qual a maior goleada da história do Colo-Colo num jogo da liga chilena?',
   10, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1964, 'pending'),
  ('Qual a maior goleada da história da Universidad de Chile num jogo da liga chilena?',
   9, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1969, 'pending'),
  ('Qual a maior goleada da história do Atlético Nacional num jogo da liga colombiana?',
   8, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1991, 'pending'),
  ('Qual a maior goleada da história do Alianza Lima num jogo da liga peruana?',
   9, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1963, 'pending'),
  ('Qual a maior goleada da história do Olimpia num jogo da liga paraguaia?',
   8, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1955, 'pending'),
  ('Qual a maior goleada da história do Barcelona SC num jogo da liga equatoriana?',
   7, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1972, 'pending'),
  ('Qual a maior goleada da história do Bolívar num jogo da liga boliviana?',
   8, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1980, 'pending'),

-- Família 12: transferência de saída mais cara da história do clube
  ('Qual a transferência de saída mais cara da história do River Plate, com Julián Álvarez indo para o Manchester City?',
   20, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Qual a transferência de saída mais cara da história do Racing Club, com Lautaro Martínez indo para a Inter de Milão?',
   22, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2018, 'pending'),
  ('Qual a transferência de saída mais cara da história do Independiente, com Sergio Agüero indo para o Atlético de Madrid?',
   23, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2006, 'pending'),
  ('Qual a transferência de saída mais cara da história do Boca Juniors?',
   10, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Qual a transferência de saída mais cara da história do Peñarol, com Nahitan Nández indo para o Cagliari?',
   9, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Qual a transferência de saída mais cara da história do Nacional, do Uruguai, com Rodrigo Bentancur indo para a Juventus?',
   9, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2017, 'pending'),
  ('Qual a transferência de saída mais cara da história do Colo-Colo, com Gary Medel indo para o Sevilla?',
   8, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('Qual a transferência de saída mais cara da história da Universidad de Chile, com Charles Aránguiz indo para o futebol europeu?',
   6, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Qual a transferência de saída mais cara da história do Atlético Nacional, da Colômbia?',
   5, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2018, 'pending'),
  ('Qual a transferência de saída mais cara da história do Barcelona SC, do Equador?',
   4, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),

-- Família 13: público recorde do estádio do clube (maior comparecimento já registrado)
  ('Qual o maior público já registrado no Estádio Centenário, em Montevidéu, na final da Copa do Mundo de 1930?',
   93000, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1930, 'pending'),
  ('Qual o maior público já registrado no Estádio Monumental, casa do River Plate, na Argentina?',
   84567, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1976, 'pending'),
  ('Qual o maior público já registrado na Bombonera, casa do Boca Juniors, na Argentina?',
   57395, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1976, 'pending'),
  ('Qual o maior público já registrado no Estádio Nacional do Chile, em Santiago, antes das reformas de segurança?',
   80000, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1962, 'pending'),
  ('Qual o maior público já registrado no Estádio El Campín, em Bogotá, na Colômbia?',
   52000, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1983, 'pending'),
  ('Qual o maior público já registrado no antigo Estádio Nacional do Peru, em Lima, antes da reforma?',
   60000, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1970, 'pending'),
  ('Qual o maior público já registrado no Estádio Defensores del Chaco, casa da seleção paraguaia?',
   42354, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1998, 'pending'),
  ('Qual o maior público já registrado no Estádio Monumental Banco Pichincha, casa do Barcelona SC, no Equador?',
   60000, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2008, 'pending'),
  ('Qual o maior público já registrado no Estádio Hernando Siles, em La Paz, na Bolívia?',
   45000, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1997, 'pending'),
  ('Qual o maior público já registrado no Estádio Olímpico da UCV, em Caracas, na Venezuela?',
   42000, 'pessoas', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2007, 'pending'),

-- Família 14: ano do último título de liga do clube (jejum de clube tradicional)
  ('O Racing Club, da Argentina, ficou mais de uma década sem título nacional antes de voltar a vencer. Em que ano ele encerrou esse jejum?',
   2014, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('O San Lorenzo, da Argentina, ficou muitos anos sem título nacional antes de voltar a vencer. Em que ano ele encerrou esse jejum?',
   2013, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2013, 'pending'),
  ('O Estudiantes de La Plata, da Argentina, ficou anos sem título de liga antes de voltar a vencer. Em que ano ele encerrou esse jejum?',
   2010, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('A Universidad Católica, do Chile, ficou anos sem título nacional antes de voltar a vencer. Em que ano ela encerrou esse jejum?',
   2016, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2016, 'pending'),
  ('O Millonarios, da Colômbia, ficou mais de duas décadas sem título nacional antes de voltar a vencer. Em que ano ele encerrou esse longo jejum?',
   2012, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2012, 'pending'),
  ('O Universitario de Deportes, do Peru, ficou anos sem título nacional antes de voltar a vencer. Em que ano ele encerrou esse jejum?',
   2013, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2013, 'pending'),
  ('O Cerro Porteño, do Paraguai, ficou anos sem título nacional antes de voltar a vencer. Em que ano ele encerrou esse jejum?',
   2013, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2013, 'pending'),
  ('O Deportivo Quito, do Equador, teve seu auge e depois enfrentou um jejum de títulos. Em que ano foi o último título de liga do clube?',
   2010, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('O Deportivo Táchira, da Venezuela, ficou um tempo sem título nacional antes de voltar a vencer. Em que ano ele encerrou esse jejum?',
   2015, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('O The Strongest, da Bolívia, ficou um tempo sem título nacional antes de voltar a vencer. Em que ano ele encerrou esse jejum?',
   2011, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2011, 'pending');
