-- RASCUNHO NÃO VERIFICADO. Todas as ~140 linhas abaixo foram escritas de memória, sem pesquisa
-- (sem WebSearch/WebFetch) — é geração de volume de candidatos, não curadoria. Todo `answer` é
-- estimativa educada; toda `source_name`/`source_url` é placeholder. status = 'pending' em toda
-- linha; start_round só sorteia status = 'approved', então nada aqui entra em partida real antes
-- de uma sessão futura confirmar cada número com fonte real e decidir aprovar/rejeitar (mesmo
-- processo usado no início do banco, ver cabeçalho de futebol_01.sql).
--
-- Foco: ligas domésticas e clubes da EUROPA, priorizando países menos óbvios (fora do eixo
-- Inglaterra/Espanha/Alemanha/Itália/França) — Holanda, Portugal, Bélgica, Escócia, Turquia,
-- Rússia/Ucrânia, países nórdicos, Europa Central e do Leste, Balcãs.
--
-- Famílias incluídas (cada uma cobre 1 métrica, variando o clube/país/jogador):
--   1.  Artilheiro histórico do clube (maior goleador de sempre) — por clube europeu obscuro
--   2.  Clube com mais títulos da liga nacional — por país europeu
--   3.  Ano de fundação do clube — clubes europeus tradicionais
--   4.  Capacidade do estádio do clube — clubes europeus
--   5.  Maior sequência de títulos consecutivos da liga nacional — por clube/país
--   6.  Maior invencibilidade numa liga nacional (jogos sem perder) — por clube
--   7.  Transferência de saída mais cara da história do clube — por clube
--   8.  Número de vezes que o clube foi campeão nacional (contagem total de títulos)
--   9.  Ano do último título de liga do clube (jejum) — clubes tradicionais em baixa
--   10. Maior artilheiro estrangeiro da história de uma liga nacional
--   11. Público recorde do estádio do clube (maior comparecimento já registrado)
--   12. Idade do jogador mais jovem a estrear pelo clube na 1ª divisão
--   13. Número de rebaixamentos já sofridos pelo clube na história
--   14. Maior goleada da história do clube num campeonato nacional

insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values

-- Família 1: artilheiro histórico do clube (maior goleador de sempre), clubes europeus menos óbvios
  ('Dennis Bergkamp é um dos maiores ídolos do Ajax. Quantos gols ele marcou pelo clube ao longo da carreira?',
   122, 'gols', 'futebol', 2, 'Wikipedia — "Dennis Bergkamp" (total de gols pelo Ajax, 239 jogos)', 'https://en.wikipedia.org/wiki/Dennis_Bergkamp', 1993, 'approved'),
  ('Eusébio é o maior artilheiro da história do Benfica. Quantos gols ele marcou pelo clube português?',
   473, 'gols', 'futebol', 2, 'Wikipedia — "List of S.L. Benfica records and statistics" (gols em todas as competições oficiais, 1961–1975)', 'https://en.wikipedia.org/wiki/List_of_S.L._Benfica_records_and_statistics', 1975, 'approved'),
  ('Paul Van Himst é lenda histórica do Anderlecht, na Bélgica. Quantos gols ele marcou pelo clube na carreira?',
   234, 'gols', 'futebol', 3, 'Wikipedia — "Paul Van Himst" (gols pelo Anderlecht na liga belga, 1959–1975; convergem infobox em inglês e neerlandês)', 'https://en.wikipedia.org/wiki/Paul_Van_Himst', 1975, 'approved'),
  ('Henrik Larsson é o maior artilheiro da história do Celtic, da Escócia. Quantos gols ele marcou pelo clube?',
   242, 'gols', 'futebol', 2, 'REJEITADA — premissa falsa: o maior artilheiro histórico do Celtic é Jimmy McGrory (522 gols), não Larsson (3º colocado, 242)', 'rejected://premissa-falsa-recordista', 2024, 'rejected'),
  ('Hakan Şükür é o maior artilheiro da história do Galatasaray, na Turquia. Quantos gols ele marcou pelo clube?',
   249, 'gols', 'futebol', 3, 'REJEITADA — premissa falsa: o maior artilheiro histórico do Galatasaray é Metin Oktay (349 gols), não Şükür', 'rejected://premissa-falsa-recordista', 2024, 'rejected'),
  ('O CSKA Moscou é um dos maiores clubes da Rússia. Quantos gols marcou pelo clube seu artilheiro histórico, Grigori Fedotov?',
   124, 'gols', 'futebol', 3, 'Wikipedia — "Grigori Fedotov" (124 gols em 155 jogos pelo CSKA Moscou, 1938–1949)', 'https://en.wikipedia.org/wiki/Grigori_Fedotov', 1949, 'approved'),
  ('O Dínamo de Kiev é o clube mais tradicional da Ucrânia. Quantos gols marcou pelo clube seu artilheiro histórico, Oleg Blokhin?',
   266, 'gols', 'futebol', 3, 'Wikipedia — "Oleh Blokhin" (recordista histórico do Dínamo de Kiev, 266 gols em todas as competições, 1969–1988)', 'https://en.wikipedia.org/wiki/Oleh_Blokhin', 1988, 'approved'),
  ('O Malmö FF é o clube sueco de maior tradição. Quantos gols marcou pelo clube seu artilheiro histórico?',
   163, 'gols', 'futebol', 3, 'Wikipedia — "List of Malmö FF records and statistics" (recordista histórico é Hans Håkansson, 163 gols em 192 jogos na liga, 1927–1938)', 'https://en.wikipedia.org/wiki/List_of_Malm%C3%B6_FF_records_and_statistics', 1938, 'approved'),
  ('O Steaua Bucareste é o clube romeno mais titulado da era comunista. Quantos gols marcou pelo clube seu artilheiro histórico?',
   146, 'gols', 'futebol', 3, 'Wikipedia (RO) — "FC Steaua București" (artilheiro histórico da liga é Anghel Iordănescu, 146 gols, 1968–1982)', 'https://ro.wikipedia.org/wiki/FC_Steaua_Bucure%C8%99ti', 1982, 'approved'),
  ('O Estrela Vermelha, de Belgrado, é o clube mais titulado da Sérvia. Quantos gols marcou pelo clube seu artilheiro histórico?',
   158, 'gols', 'futebol', 3, 'Wikipedia — "Bora Kostić" (artilheiro histórico do Estrela Vermelha, 158 gols na liga, 1951–1966)', 'https://en.wikipedia.org/wiki/Bora_Kosti%C4%87', 1966, 'approved'),

-- Família 2: clube com mais títulos da liga nacional, por país europeu
  ('Na Holanda, qual clube tem mais títulos da Eredivisie? Quantos títulos ele tem, ao todo?',
   36, 'títulos', 'futebol', 2, 'Wikipedia — "List of Dutch football champions" (Ajax lidera com 36 títulos; mais recente na temporada 2021–22)', 'https://en.wikipedia.org/wiki/List_of_Dutch_football_champions', 2022, 'approved'),
  ('Em Portugal, o Benfica é um dos maiores campeões nacionais. Quantos títulos da Primeira Liga ele já venceu?',
   38, 'títulos', 'futebol', 2, 'Wikipedia — "List of Portuguese football champions" (Benfica lidera com 38 títulos; mais recente na temporada 2022–23)', 'https://en.wikipedia.org/wiki/List_of_Portuguese_football_champions', 2023, 'approved'),
  ('Na Bélgica, o Anderlecht é o maior campeão da liga nacional. Quantos títulos ele já venceu?',
   34, 'títulos', 'futebol', 2, 'Wikipedia — "List of Belgian football champions" (Anderlecht lidera com 34 títulos; mais recente na temporada 2016–17)', 'https://en.wikipedia.org/wiki/List_of_Belgian_football_champions', 2017, 'approved'),
  ('Na Escócia, o Rangers é um dos maiores campeões nacionais da história. Quantos títulos da liga escocesa ele já venceu?',
   55, 'títulos', 'futebol', 2, 'REJEITADA — premissa falsa: o maior campeão do futebol escocês é o Celtic (56 títulos), não o Rangers (55, 2º colocado)', 'rejected://premissa-falsa-recordista', 2026, 'rejected'),
  ('Na Turquia, o Galatasaray é um dos maiores campeões nacionais. Quantos títulos do Campeonato Turco ele já venceu?',
   26, 'títulos', 'futebol', 2, 'Wikipedia — "Süper Lig" (Galatasaray é o clube mais titulado reconhecido oficialmente pela TFF desde 1959, com 26 títulos; mais recente na temporada 2024–25)', 'https://en.wikipedia.org/wiki/S%C3%BCper_Lig', 2025, 'approved'),
  ('Na Rússia, o Spartak Moscou é um dos clubes mais tradicionais. Quantos títulos do campeonato nacional (contando era soviética e pós-soviética) ele já venceu?',
   22, 'títulos', 'futebol', 3, 'Wikipedia — "List of Russian football champions" (Spartak Moscou lidera somando eras soviética e pós-soviética, com 22 títulos; mais recente na temporada 2016–17)', 'https://en.wikipedia.org/wiki/List_of_Russian_football_champions', 2017, 'approved'),
  ('Na Grécia, o Olympiacos é o maior campeão da liga nacional. Quantos títulos ele já venceu?',
   48, 'títulos', 'futebol', 2, 'Wikipedia — "List of Greek football champions" (Olympiacos lidera com 48 títulos; mais recente em 2025)', 'https://en.wikipedia.org/wiki/List_of_Greek_football_champions', 2025, 'approved'),
  ('Na Áustria, o Rapid Viena é um dos clubes mais tradicionais. Quantos títulos do campeonato nacional ele já venceu?',
   32, 'títulos', 'futebol', 3, 'Wikipedia — "List of Austrian football champions" (Rapid Viena lidera com 32 títulos; mais recente na temporada 2007–08)', 'https://en.wikipedia.org/wiki/List_of_Austrian_football_champions', 2008, 'approved'),
  ('Na Suíça, o Young Boys é um dos maiores campeões da liga nacional. Quantos títulos ele já venceu?',
   17, 'títulos', 'futebol', 3, 'REJEITADA — premissa falsa: o maior campeão do futebol suíço é o Grasshopper Club Zürich (27 títulos), não o Young Boys (17)', 'rejected://premissa-falsa-recordista', 2025, 'rejected'),
  ('Na Croácia, o Dínamo Zagreb é o clube mais dominante da liga nacional. Quantos títulos ele já venceu desde a independência do país (1991)?',
   25, 'títulos', 'futebol', 3, 'Wikipedia — "Prva HNL" (Dínamo Zagreb lidera com 25 títulos desde a independência da Croácia em 1991; mais recente na temporada 2025–26)', 'https://en.wikipedia.org/wiki/Prva_HNL', 2026, 'approved'),

-- Família 3: ano de fundação do clube, clubes tradicionais europeus
  ('Em que ano foi fundado o Ajax, um dos clubes mais tradicionais da Holanda?',
   1900, 'ano', 'futebol', 1, 'REJEITADA — morna: ano confirmado (18 mar 1900, Wikipedia), mas isolado não gera comparação, surpresa nem debate (critério 4)', 'rejected://morna-sem-gancho', 1900, 'rejected'),
  ('Em que ano foi fundado o Sporting, um dos três grandes clubes de Portugal?',
   1906, 'ano', 'futebol', 2, 'REJEITADA — morna: ano confirmado (1 jul 1906, Wikipedia), mas isolado não gera comparação, surpresa nem debate (critério 4)', 'rejected://morna-sem-gancho', 1906, 'rejected'),
  ('Em que ano foi fundado o Club Brugge, um dos maiores clubes da Bélgica?',
   1891, 'ano', 'futebol', 2, 'REJEITADA — morna: ano confirmado (13 nov 1891, Wikipedia), mas isolado não gera comparação, surpresa nem debate (critério 4)', 'rejected://morna-sem-gancho', 1891, 'rejected'),
  ('Em que ano foi fundado o Celtic, um dos clubes mais tradicionais da Escócia?',
   1887, 'ano', 'futebol', 2, 'REJEITADA — morna: ano confirmado (6 nov 1887, Wikipedia); a origem beneficente (Irmão Walfrid) é interessante, mas o texto pergunta só o ano isolado, sem esse gancho (critério 4)', 'rejected://morna-sem-gancho', 1887, 'rejected'),
  ('Em que ano foi fundado o Fenerbahçe, um dos maiores clubes da Turquia?',
   1907, 'ano', 'futebol', 2, 'REJEITADA — morna: ano confirmado (3 mai 1907, Wikipedia); a fundação clandestina sob o sultão otomano é interessante, mas o texto pergunta só o ano isolado, sem esse gancho (critério 4)', 'rejected://morna-sem-gancho', 1907, 'rejected'),
  ('Em que ano foi fundado o Estrela Vermelha, de Belgrado, o clube mais titulado da Sérvia?',
   1945, 'ano', 'futebol', 2, 'Wikipedia — "Red Star Belgrade" (fundado em 4 de março de 1945, em Belgrado, por jovens da Liga Antifascista da Juventude Sérvia, já sob a reorganização comunista do pós-guerra)', 'https://en.wikipedia.org/wiki/Red_Star_Belgrade', 1945, 'approved'),
  ('Em que ano foi fundado o Rosenborg, o clube mais dominante da Noruega?',
   1917, 'ano', 'futebol', 3, 'REJEITADA — morna: ano confirmado (19 mai 1917, como "Odd", rebatizado Rosenborg em 1928, Wikipedia), mas isolado não gera comparação, surpresa nem debate (critério 4)', 'rejected://morna-sem-gancho', 1917, 'rejected'),
  ('Em que ano foi fundado o Malmö FF, o clube sueco de maior tradição?',
   1910, 'ano', 'futebol', 3, 'REJEITADA — morna: ano confirmado (24 fev 1910, Wikipedia), mas isolado não gera comparação, surpresa nem debate (critério 4)', 'rejected://morna-sem-gancho', 1910, 'rejected'),
  ('Em que ano foi fundado o Ferencváros, o clube mais titulado da Hungria?',
   1899, 'ano', 'futebol', 2, 'REJEITADA — morna: ano confirmado (3 mai 1899, Wikipedia), mas isolado não gera comparação, surpresa nem debate (critério 4)', 'rejected://morna-sem-gancho', 1899, 'rejected'),
  ('Em que ano foi fundado o Legia Varsóvia, um dos maiores clubes da Polônia?',
   1916, 'ano', 'futebol', 3, 'REJEITADA — morna: ano confirmado (mar 1916, fundado por soldados da Legião Polonesa na frente da 1ª Guerra, Wikipedia); origem militar é interessante, mas o texto pergunta só o ano isolado, sem esse gancho (critério 4)', 'rejected://morna-sem-gancho', 1916, 'rejected'),

-- Família 4: capacidade do estádio do clube
  ('Qual a capacidade da Johan Cruyff Arena, estádio do Ajax, na Holanda?',
   55865, 'lugares', 'futebol', 2, 'Wikipédia — "Johan Cruijff Arena" (capacidade atual do infobox, 55.865 lugares, após a última obra de ampliação de 2025)', 'https://en.wikipedia.org/wiki/Johan_Cruijff_Arena', 2025, 'approved'),
  ('Qual a capacidade do Estádio da Luz, casa do Benfica, em Lisboa?',
   68100, 'lugares', 'futebol', 2, 'Wikipédia — "Estádio da Luz" (capacidade após a 1ª fase da obra de expansão concluída em 11/jul/2025, confirmada em pt. e en.wikipedia)', 'https://pt.wikipedia.org/wiki/Est%C3%A1dio_da_Luz', 2025, 'approved'),
  ('Qual a capacidade do Ibrox Stadium, casa do Rangers, na Escócia?',
   51700, 'lugares', 'futebol', 2, 'Wikipédia — "Ibrox Stadium" (capacidade após a ampliação do Copland Rear em set/2024)', 'https://en.wikipedia.org/wiki/Ibrox_Stadium', 2024, 'approved'),
  ('Qual a capacidade do estádio Ali Sami Yen (NEF Stadyumu/Rams Park), casa do Galatasaray, na Turquia?',
   53387, 'lugares', 'futebol', 3, 'Wikipédia — "Rams Park" (nome oficial completo Ali Sami Yen Spor Kompleksi; capacidade vigente desde 2026)', 'https://en.wikipedia.org/wiki/Rams_Park', 2026, 'approved'),
  ('Qual a capacidade do Estádio Marakana, casa do Estrela Vermelha, na Sérvia?',
   49167, 'lugares', 'futebol', 3, 'Wikipédia — "Rajko Mitić Stadium" (capacidade oficial, citando o site do Estrela Vermelha, consultado em jun/2025)', 'https://en.wikipedia.org/wiki/Rajko_Miti%C4%87_Stadium', 2025, 'approved'),
  ('Qual a capacidade do Lotto Park, casa do Anderlecht, na Bélgica?',
   21500, 'lugares', 'futebol', 3, 'Wikipédia — "Lotto Park" (capacidade reduzida ao padrão UEFA na reforma de 2012)', 'https://en.wikipedia.org/wiki/Lotto_Park', 2012, 'approved'),
  ('Qual a capacidade do Estádio Luzhniki, o maior estádio da Rússia, em Moscou?',
   81000, 'lugares', 'futebol', 2, 'Wikipédia — "Luzhniki Stadium" (capacidade pós-reconstrução para a Copa de 2018, concluída em 2017; maior estádio de futebol da Rússia)', 'https://en.wikipedia.org/wiki/Luzhniki_Stadium', 2017, 'approved'),
  ('Qual a capacidade do Groupama Arena, casa do Ferencváros, na Hungria?',
   23700, 'lugares', 'futebol', 3, 'Wikipédia — "Groupama Aréna" (capacidade desde a inauguração em ago/2014; 22.122 para jogos internacionais)', 'https://en.wikipedia.org/wiki/Groupama_Ar%C3%A9na', 2014, 'approved'),
  ('Qual a capacidade do Lerkendal Stadion, casa do Rosenborg, na Noruega?',
   21423, 'lugares', 'futebol', 3, 'Wikipédia — "Lerkendal Stadion" (capacidade após a reforma concluída em 2002)', 'https://en.wikipedia.org/wiki/Lerkendal_Stadion', 2002, 'approved'),
  ('Qual a capacidade do Estádio Maksimir, casa do Dínamo Zagreb, na Croácia?',
   24851, 'lugares', 'futebol', 3, 'Wikipédia (HR) — "Stadion Maksimir" (capacidade reduzida desde o terremoto de Zagreb de mar/2020, com a tribuna leste ainda interditada; artigo atualizado em jul/2026)', 'https://hr.wikipedia.org/wiki/Stadion_Maksimir', 2020, 'approved'),

-- Família 5: maior sequência de títulos consecutivos da liga nacional
  ('O Ajax teve uma fase dominante na Eredivisie. Qual a maior sequência de títulos seguidos que o clube já teve?',
   4, 'títulos seguidos', 'futebol', 3, 'Wikipedia — "List of Dutch football champions" (Ajax venceu 4 títulos seguidos entre 2010–11 e 2013–14; recorde do país, empatado com o PSV Eindhoven)', 'https://en.wikipedia.org/wiki/List_of_Dutch_football_champions', 2014, 'approved'),
  ('O Porto teve um período de domínio na Primeira Liga portuguesa. Qual a maior sequência de títulos seguidos do clube?',
   5, 'títulos seguidos', 'futebol', 3, 'Wikipedia — "List of Portuguese football champions" (Porto venceu 5 títulos seguidos entre 1995 e 1999; maior sequência do país)', 'https://en.wikipedia.org/wiki/List_of_Portuguese_football_champions', 1999, 'approved'),
  ('O Celtic dominou a liga escocesa na década de 2010. Qual a maior sequência de títulos seguidos que o clube já teve?',
   9, 'títulos seguidos', 'futebol', 2, 'Wikipedia — "List of Scottish football champions" (Celtic venceu 9 títulos seguidos entre 2011–12 e 2019–20; recorde do país, igualado pelo próprio Celtic em 1966–1974 e pelo Rangers em 1989–1997)', 'https://en.wikipedia.org/wiki/List_of_Scottish_football_champions', 2020, 'approved'),
  ('O Rosenborg dominou o futebol norueguês nos anos 1990-2000. Qual a maior sequência de títulos seguidos que o clube já teve?',
   13, 'títulos seguidos', 'futebol', 2, 'Wikipedia — "List of Norwegian football champions" (Rosenborg venceu 13 títulos seguidos entre 1992 e 2004; recorde do país)', 'https://en.wikipedia.org/wiki/List_of_Norwegian_football_champions', 2004, 'approved'),
  ('O BATE Borisov dominou o futebol bielorrusso do fim dos anos 2000 ao fim dos anos 2010. Qual a maior sequência de títulos seguidos que o clube já teve?',
   13, 'títulos seguidos', 'futebol', 3, 'Wikipedia — "Belarusian Premier League" (BATE Borisov venceu 13 títulos seguidos entre 2006 e 2018; recorde do país)', 'https://en.wikipedia.org/wiki/Belarusian_Premier_League', 2018, 'approved'),
  ('O Dínamo Zagreb dominou o futebol croata de meados dos anos 2000 a meados dos anos 2010. Qual a maior sequência de títulos seguidos que o clube já teve?',
   11, 'títulos seguidos', 'futebol', 3, 'Wikipedia — "Croatian Football League" (Dínamo Zagreb venceu 11 títulos seguidos entre 2005–06 e 2015–16; recorde do país)', 'https://en.wikipedia.org/wiki/Croatian_Football_League', 2016, 'approved'),
  ('O Ludogorets dominou o futebol búlgaro da década de 2010 até meados dos anos 2020. Qual a maior sequência de títulos seguidos que o clube já teve?',
   14, 'títulos seguidos', 'futebol', 3, 'Wikipedia — "List of Bulgarian football champions" (Ludogorets venceu 14 títulos seguidos entre 2011–12 e 2024–25, sequência interrompida pelo Levski Sofia em 2025–26; recorde do país)', 'https://en.wikipedia.org/wiki/List_of_Bulgarian_football_champions', 2025, 'approved'),
  ('O Zenit dominou o futebol russo na década de 2010-2020. Qual a maior sequência de títulos seguidos que o clube já teve?',
   6, 'títulos seguidos', 'futebol', 3, 'Wikipedia — "List of Soviet and Russian football champions" (Zenit venceu 6 títulos seguidos entre 2018–19 e 2023–24; recorde do país na era pós-soviética, igualado pelo Spartak Moscou em 1996–2001)', 'https://en.wikipedia.org/wiki/List_of_Soviet_and_Russian_football_champions', 2024, 'approved'),
  ('O F91 Dudelange dominou o futebol de Luxemburgo na década de 2000. Qual a maior sequência de títulos seguidos que o clube já teve?',
   5, 'títulos seguidos', 'futebol', 3, 'Wikipedia — "Luxembourg National Division" (F91 Dudelange venceu 5 títulos seguidos entre 2004–05 e 2008–09; recorde do país, igualado pelo Jeunesse Esch)', 'https://en.wikipedia.org/wiki/Luxembourg_National_Division', 2009, 'approved'),
  ('O Shakhtar Donetsk dominou o futebol ucraniano nos anos 2010. Qual a maior sequência de títulos seguidos que o clube já teve?',
   6, 'títulos seguidos', 'futebol', 3, 'REJEITADA — premissa falsa: a sequência do Shakhtar é 5 títulos seguidos (2009–10 a 2013–14), não 6, e o recorde ucraniano pertence ao Dínamo de Kiev (9 seguidos, 1992–93 a 2000–01)', 'rejected://premissa-falsa-shakhtar-sequencia', 2024, 'rejected'),

-- Família 6: maior invencibilidade numa liga nacional (jogos sem perder)
  ('O Celtic teve uma sequência longa de jogos sem perder na liga escocesa. Qual o recorde de jogos seguidos invicto do clube?',
   62, 'jogos', 'futebol', 3, 'REJEITADA — gancho de invencibilidade já saturado no banco (4+ perguntas aprovadas anteriormente), família reprovada por redundância de forma', 'rejected://gancho-saturado-invencibilidade', 2017, 'rejected'),
  ('O Porto quebrou o próprio recorde de invencibilidade da Primeira Liga portuguesa entre 2020 e 2022, sob o técnico Sérgio Conceição. Quantos jogos seguidos o clube ficou sem perder?',
   58, 'jogos', 'futebol', 3, 'Wikipedia (FC Porto) — recorde de 58 jogos sem perder na Primeira Liga, sequência iniciada na 1ª metade de 2020–21 e batida na temporada 2021–22', 'https://en.wikipedia.org/wiki/FC_Porto', 2022, 'approved'),
  ('O Ludogorets teve uma sequência longa de invencibilidade no campeonato búlgaro. Qual o recorde de jogos seguidos sem perder?',
   70, 'jogos', 'futebol', 3, 'REJEITADA — gancho de invencibilidade já saturado no banco (4+ perguntas aprovadas anteriormente), família reprovada por redundância de forma', 'rejected://gancho-saturado-invencibilidade', 2018, 'rejected'),
  ('O Ajax de 1994/95, comandado por Louis van Gaal, é até hoje o único time da história a terminar uma temporada inteira da Eredivisie sem perder. Quantos jogos teve essa temporada?',
   34, 'jogos', 'futebol', 3, 'Wikipedia (1994–95 Eredivisie) — 27 vitórias e 7 empates em 34 jogos, único time a completar uma temporada inteira da Eredivisie invicto', 'https://en.wikipedia.org/wiki/1994%E2%80%9395_Eredivisie', 1995, 'approved'),
  ('O BATE Borisov teve longas sequências invictas no campeonato bielorrusso. Qual o recorde de jogos seguidos sem perder do clube?',
   50, 'jogos', 'futebol', 3, 'REJEITADA — gancho de invencibilidade já saturado no banco (4+ perguntas aprovadas anteriormente), família reprovada por redundância de forma', 'rejected://gancho-saturado-invencibilidade', 2015, 'rejected'),
  ('Na temporada 2014/15, o Dínamo Zagreb protagonizou a única campanha invicta da história do campeonato croata. Quantos jogos teve essa temporada sem nenhuma derrota?',
   36, 'jogos', 'futebol', 3, 'Wikipedia (2014–15 Croatian First Football League) — 26 vitórias e 10 empates em 36 jogos, única temporada invicta da história do campeonato croata', 'https://en.wikipedia.org/wiki/2014%E2%80%9315_Croatian_First_Football_League', 2015, 'approved'),
  ('O Rangers teve uma sequência invicta longa na liga escocesa. Qual o recorde de jogos seguidos sem perder do clube?',
   44, 'jogos', 'futebol', 3, 'REJEITADA — gancho de invencibilidade já saturado no banco (4+ perguntas aprovadas anteriormente), família reprovada por redundância de forma', 'rejected://gancho-saturado-invencibilidade', 2021, 'rejected'),
  ('O Shakhtar Donetsk teve uma sequência de invencibilidade marcante no campeonato ucraniano. Qual o recorde de jogos seguidos sem perder do clube?',
   40, 'jogos', 'futebol', 3, 'REJEITADA — gancho de invencibilidade já saturado no banco (4+ perguntas aprovadas anteriormente), família reprovada por redundância de forma', 'rejected://gancho-saturado-invencibilidade', 2014, 'rejected'),
  ('O Rosenborg teve uma sequência de invencibilidade marcante na liga norueguesa nos anos 2000. Qual o recorde de jogos seguidos sem perder do clube?',
   38, 'jogos', 'futebol', 3, 'REJEITADA — gancho de invencibilidade já saturado no banco (4+ perguntas aprovadas anteriormente), família reprovada por redundância de forma', 'rejected://gancho-saturado-invencibilidade', 2004, 'rejected'),
  ('O Zenit teve uma longa sequência invicta na liga russa. Qual o recorde de jogos seguidos sem perder do clube?',
   32, 'jogos', 'futebol', 3, 'REJEITADA — gancho de invencibilidade já saturado no banco (4+ perguntas aprovadas anteriormente), família reprovada por redundância de forma', 'rejected://gancho-saturado-invencibilidade', 2020, 'rejected'),

-- Família 7: transferência de saída mais cara da história do clube
  ('Qual a transferência de saída mais cara da história do Ajax (valor pago pelo clube comprador)?',
   95, 'milhões de euros', 'futebol', 2, 'BBC Sport', 'https://www.bbc.co.uk/sport/football/62718027', 2022, 'approved'),
  ('Qual a transferência de saída mais cara da história do Benfica?',
   126, 'milhões de euros', 'futebol', 2, 'The Guardian', 'https://www.theguardian.com/football/2019/jul/03/atletico-madrid-sign-benfica-teenager-joao-felix-for-fee-of-126m', 2019, 'approved'),
  ('Qual a transferência de saída mais cara da história do Sporting, de Portugal?',
   70, 'milhões de euros', 'futebol', 3, 'A Bola', 'https://www.abola.pt/noticias/da-transferencia-conturbada-a-final-da-champions-os-bonus-milionarios-que-gyokeres-ja-rendeu-ao-sporting-2026050610004187282', 2025, 'approved'),
  ('Qual a transferência de saída mais cara da história do Club Brugge, da Bélgica?',
   32, 'milhões de euros', 'futebol', 3, 'REJEITADA — sem fonte citável específica para o valor (candidato De Ketelaere ~€35M): Transfermarkt bloqueado para acesso nesta sessão, Wikipedia EN/IT citam a cifra sem referência atrelada, e a única fonte alternativa encontrada diverge (€28M) sem citar origem primária', 'rejected://club-brugge-sem-fonte-confiavel', 2022, 'rejected'),
  ('Qual a transferência de saída mais cara da história do Celtic, da Escócia?',
   25, 'milhões de libras', 'futebol', 3, 'BBC Sport', 'https://www.bbc.co.uk/sport/football/49283667', 2019, 'approved'),
  ('Qual a transferência de saída mais cara da história do Galatasaray, da Turquia?',
   30, 'milhões de euros', 'futebol', 3, 'Reuters', 'https://www.reuters.com/sports/soccer/bayern-sign-defender-sacha-boey-galatasaray-until-2028-2024-01-28/', 2024, 'approved'),
  ('Qual a transferência de saída mais cara da história do Shakhtar Donetsk, da Ucrânia?',
   70, 'milhões de euros', 'futebol', 3, 'FC Shakhtar Donetsk (comunicado oficial)', 'https://shakhtar.com/en/news/2023/january/15_news/15_thanks_mykhailo-mudryk/', 2023, 'approved'),
  ('Qual a transferência de saída mais cara da história do Red Bull Salzburg, da Áustria?',
   45, 'milhões de euros', 'futebol', 3, 'REJEITADA — sem fonte citável específica para o valor (candidato Adeyemi €30M aparece só em tabela do Wikipedia sem referência atrelada; Transfermarkt bloqueado nesta sessão; nenhuma matéria dedicada encontrada confirmando a cifra)', 'rejected://salzburg-sem-fonte-confiavel', 2022, 'rejected'),
  ('Qual a transferência de saída mais cara da história do Anderlecht, da Bélgica?',
   25, 'milhões de euros', 'futebol', 3, 'Sky Sports', 'https://www.skysports.com/football/news/11816/10891820/monaco-have-confirmed-the-signing-of-youri-tielemans-on-a-five-year-deal', 2017, 'approved'),
  ('Qual a transferência de saída mais cara da história do AZ Alkmaar, da Holanda?',
   18, 'milhões de euros', 'futebol', 3, 'A Bola', 'https://www.abola.pt/futebol/noticias/oficial-pavlidis-reforca-benfica-2024070113071840308', 2024, 'approved'),

-- Família 8: número total de títulos nacionais conquistados pelo clube
  ('Quantos títulos do Campeonato Português o Porto já venceu, ao todo?',
   31, 'títulos', 'futebol', 2, 'Wikipedia — "List of Portuguese football champions" (Porto soma 31 títulos, atrás do líder Benfica com 38; mais recente na temporada 2025–26)', 'https://en.wikipedia.org/wiki/List_of_Portuguese_football_champions', 2026, 'approved'),
  ('Quantos títulos da Eredivisie o PSV Eindhoven já venceu, ao todo?',
   27, 'títulos', 'futebol', 2, 'Wikipedia — "List of Dutch football champions" (PSV Eindhoven soma 27 títulos, atrás do líder Ajax; mais recente na temporada 2025–26)', 'https://en.wikipedia.org/wiki/List_of_Dutch_football_champions', 2026, 'approved'),
  ('Quantos títulos da liga escocesa o Celtic já venceu, ao todo?',
   56, 'títulos', 'futebol', 2, 'Wikipedia — "List of Scottish football champions" (Celtic lidera o país com 56 títulos, à frente do Rangers com 55; mais recente na temporada 2025–26)', 'https://en.wikipedia.org/wiki/List_of_Scottish_football_champions', 2026, 'approved'),
  ('Quantos títulos da liga turca o Fenerbahçe já venceu, ao todo?',
   19, 'títulos', 'futebol', 3, 'Wikipedia — "Süper Lig" (Fenerbahçe soma 19 títulos oficialmente reconhecidos, sem disputa de contagem; mais recente na temporada 2013–14)', 'https://en.wikipedia.org/wiki/S%C3%BCper_Lig', 2014, 'approved'),
  ('Quantos títulos nacionais (contando era soviética e russa) o Dínamo Kiev já venceu, ao todo?',
   16, 'títulos', 'futebol', 3, 'REJEITADA — premissa e número errados: o Dínamo Kiev é ucraniano e nunca disputou liga russa (o texto deveria dizer "era soviética e ucraniana"); a soma real é 13 títulos soviéticos + 17 ucranianos = 30, bem distante do candidato (16)', 'rejected://dinamo-kiev-premissa-e-numero-errados', 2016, 'rejected'),
  ('Quantos títulos da liga sueca o Malmö FF já venceu, ao todo?',
   24, 'títulos', 'futebol', 3, 'Wikipedia — "List of Swedish football champions" (Malmö FF detém o recorde do país com 24 títulos; mais recente em 2024)', 'https://en.wikipedia.org/wiki/List_of_Swedish_football_champions', 2024, 'approved'),
  ('Quantos títulos da liga húngara o Ferencváros já venceu, ao todo?',
   36, 'títulos', 'futebol', 3, 'Wikipedia — "List of Hungarian football champions" (Ferencváros lidera o país com 36 títulos; mais recente na temporada 2024–25)', 'https://en.wikipedia.org/wiki/List_of_Hungarian_football_champions', 2025, 'approved'),
  ('Quantos títulos da liga romena o Steaua Bucareste já venceu, ao todo?',
   26, 'títulos', 'futebol', 3, 'REJEITADA — disputa jurídica não resolvida: desde 2017 o clube joga como FCSB, e a titularidade do histórico do Steaua anterior a 2017 é contestada na justiça pelo CSA Steaua (ligado ao Ministério da Defesa romeno); fontes divergem entre 27 e 28 títulos e o veredito final do litígio ainda está pendente, sem número estável para gravar', 'rejected://steaua-fcsb-disputa-juridica', 2025, 'rejected'),
  ('Quantos títulos da liga búlgara o CSKA Sófia já venceu, ao todo?',
   31, 'títulos', 'futebol', 3, 'Wikipedia — "List of Bulgarian football champions" (CSKA Sófia soma 31 títulos; mais recente na temporada 2007–08)', 'https://en.wikipedia.org/wiki/List_of_Bulgarian_football_champions', 2008, 'approved'),
  ('Quantos títulos da liga polonesa o Legia Varsóvia já venceu, ao todo?',
   15, 'títulos', 'futebol', 3, 'Wikipedia — "List of Polish football champions" (Legia Varsóvia detém o recorde do país com 15 títulos; mais recente na temporada 2020–21)', 'https://en.wikipedia.org/wiki/List_of_Polish_football_champions', 2021, 'approved'),

-- Família 9: ano do último título de liga do clube (jejum de clube tradicional em baixa)
  ('O Rapid Viena é um dos clubes mais tradicionais da Áustria, mas está sem título nacional há um bom tempo. Em que ano foi o último título de liga do clube?',
   2008, 'ano', 'futebol', 3, 'Wikipedia — "List of Austrian football champions" (último título do Rapid Wien foi na temporada 2007–08; sem conquistar desde então, confirmado até a temporada 2025–26)', 'https://en.wikipedia.org/wiki/List_of_Austrian_football_champions', 2026, 'approved'),
  ('O Feyenoord tem tradição na Holanda, mas passou anos sem título antes de voltar a vencer. Em que ano ele conquistou seu título de liga mais recente antes de 2023?',
   2017, 'ano', 'futebol', 3, 'Wikipedia — "List of Eredivisie champions" (Feyenoord venceu a Eredivisie na temporada 2016–17, título imediatamente anterior ao de 2022–23)', 'https://en.wikipedia.org/wiki/List_of_Eredivisie_champions', 2023, 'approved'),
  ('O Sporting, de Portugal, ficou muito tempo sem título de liga antes de voltar a vencer em 2021. Qual foi o ano do título anterior?',
   2002, 'ano', 'futebol', 3, 'Wikipedia — "List of Portuguese football champions" (Sporting venceu a Primeira Liga em 2002, título imediatamente anterior ao de 2020–21)', 'https://en.wikipedia.org/wiki/List_of_Portuguese_football_champions', 2021, 'approved'),
  ('O Standard de Liège é um clube tradicional da Bélgica, mas está há bastante tempo sem título nacional. Em que ano foi o último título de liga do clube?',
   2009, 'ano', 'futebol', 3, 'Wikipedia — "List of Belgian football champions" (último título do Standard de Liège foi na temporada 2008–09; sem conquistar desde então, confirmado até a temporada 2025–26)', 'https://en.wikipedia.org/wiki/List_of_Belgian_football_champions', 2026, 'approved'),
  ('O Hearts, da Escócia, é um clube tradicional que está há muitas décadas sem título de liga. Em que ano foi o último título do clube?',
   1960, 'ano', 'futebol', 3, 'Wikipedia — "List of Scottish football champions" (último título do Hearts foi na temporada 1959–60; sem conquistar desde então, confirmado até a temporada 2025–26 — 66 anos de jejum)', 'https://en.wikipedia.org/wiki/List_of_Scottish_football_champions', 2026, 'approved'),
  ('O Trabzonspor é um dos poucos clubes turcos fora de Istambul a já ter sido campeão nacional, mas ficou muitos anos sem repetir o feito. Em que ano ele voltou a ser campeão, depois de décadas de jejum?',
   2022, 'ano', 'futebol', 3, 'Wikipedia — "List of Turkish football champions" (Trabzonspor voltou a ser campeão na temporada 2021–22, encerrando jejum de 40 anos desde o título de 1980–81)', 'https://en.wikipedia.org/wiki/List_of_Turkish_football_champions', 2022, 'approved'),
  ('O Spartak Moscou é um clube tradicional da Rússia, mas está há bastante tempo sem título nacional. Em que ano foi o último título de liga do clube?',
   2017, 'ano', 'futebol', 3, 'Wikipedia — "List of Russian football champions" (último título do Spartak Moscou foi na temporada 2016–17; sem conquistar desde então, confirmado até a temporada 2025–26, quando terminou em 4º lugar)', 'https://en.wikipedia.org/wiki/List_of_Russian_football_champions', 2026, 'approved'),
  ('O Hajduk Split é um dos clubes mais tradicionais da Croácia, mas nunca foi campeão desde a independência do país. Há quantos anos o clube não é campeão nacional, contando desde 1991?',
   34, 'anos', 'futebol', 3, 'REJEITADA — premissa falsa: o Hajduk Split venceu o campeonato croata 6 vezes desde a independência (1991–92, 1993–94, 1994–95, 2000–01, 2003–04, 2004–05, conforme Wikipedia — "HNK Hajduk Split" e "Croatian Football League"), a mais recente em 2004–05; não é "nunca campeão desde a independência"', 'rejected://hajduk-split-premissa-falsa', 2025, 'rejected'),
  ('O Dínamo Bucareste é um clube tradicional da Romênia, mas está há bastante tempo sem título nacional. Em que ano foi o último título de liga do clube?',
   2007, 'ano', 'futebol', 3, 'Wikipedia — "List of Romanian football champions" (último título do Dinamo București foi na temporada 2006–07; sem conquistar desde então, confirmado até a temporada 2025–26)', 'https://en.wikipedia.org/wiki/List_of_Romanian_football_champions', 2026, 'approved'),
  ('O Levski Sófia é um dos maiores clubes da Bulgária, mas ficou mais de quinze anos sem título nacional. Em que ano ele voltou a ser campeão, encerrando o jejum?',
   2026, 'ano', 'futebol', 3, 'Wikipedia — "List of Bulgarian football champions" (Levski Sófia venceu a First League 2025–26, seu 27º título, encerrando jejum desde a conquista de 2008–09 — o candidato original apontava jejum ainda em curso, dado desatualizado por essa conquista recente)', 'https://en.wikipedia.org/wiki/List_of_Bulgarian_football_champions', 2026, 'approved'),

-- Família 10: maior artilheiro estrangeiro da história de uma liga nacional
  ('O norueguês Hallvar Thoresen jogou pelo FC Twente nos anos 1970 e 80 e é, segundo a Wikipedia, o maior artilheiro estrangeiro da história da Eredivisie holandesa. Quantos gols ele marcou na competição?',
   152, 'gols', 'futebol', 3, 'Wikipedia — "List of Eredivisie top scorers" (tabela all-time: Hallvar Thoresen é o não-neerlandês com mais gols da história da liga, 152, à frente de qualquer outro estrangeiro; o candidato original citava 180 sem nomear o jogador, número não sustentado pela fonte)', 'https://en.wikipedia.org/wiki/List_of_Eredivisie_top_scorers', 2026, 'approved'),
  ('Quantos gols o brasileiro Jardel marcou pelo Porto na Primeira Liga portuguesa, um dos maiores números de um estrangeiro na competição?',
   129, 'gols', 'futebol', 3, 'Wikipedia — "Mário Jardel" (129 gols em 125 jogos pelo Porto entre 1996–97 e 1999–2000, artilheiro do campeonato português em quatro dessas temporadas; candidato original citava 130, um gol acima do total apurado)', 'https://en.wikipedia.org/wiki/M%C3%A1rio_Jardel', 2000, 'approved'),
  ('Quantos gols o brasileiro Mário Jardel marcou na liga escocesa jogando pelo Rangers, um número alto pra estrangeiro na competição?',
   30, 'gols', 'futebol', 2, 'REJEITADA — premissa falsa: Mário Jardel nunca jogou pelo Rangers; segundo a Wikipedia, uma tentativa de transferência em 1996 fracassou por regras britânicas para jogadores de fora da UE, e ele assinou com o Porto em seu lugar', 'rejected://jardel-rangers-nunca-existiu', 2003, 'rejected'),
  ('O sérvio Mateja Kežman é um dos maiores artilheiros estrangeiros da história da Eredivisie, jogando pelo PSV. Quantos gols ele marcou na liga?',
   105, 'gols', 'futebol', 3, 'Wikipedia — "Mateja Kežman" (105 gols em 122 jogos pelo PSV entre 2000–01 e 2003–04, artilheiro da Eredivisie em três dessas quatro temporadas; número do candidato confirmado exatamente)', 'https://en.wikipedia.org/wiki/Mateja_Ke%C5%BEman', 2004, 'approved'),
  ('O brasileiro Alex é, segundo a Wikipedia, o maior artilheiro estrangeiro da história do Campeonato Turco, jogando pelo Fenerbahçe. Quantos gols ele marcou na liga?',
   136, 'gols', 'futebol', 3, 'Wikipedia — "Alex (footballer, born 1977)" (136 gols em 245 jogos na Süper Lig, descrito como "the highest-scoring foreign player of all time in the Süper Lig"; candidato original citava 116, bem abaixo do total real — mantida a alegação de recorde por ser verdadeira)', 'https://en.wikipedia.org/wiki/Alex_(footballer,_born_1977)', 2012, 'approved'),
  ('Quantos gols o brasileiro Marcelinho Paraíba marcou na liga turca jogando por diversos clubes?',
   90, 'gols', 'futebol', 3, 'REJEITADA — premissa falsa: segundo a Wikipedia, Marcelinho Paraíba jogou por apenas um clube turco (Trabzonspor, 2006), marcando 2 gols em 17 jogos — nada de "diversos clubes" nem de número alto', 'rejected://marcelinho-paraiba-turquia-fabricado', 2010, 'rejected'),
  ('O croata Davor Šuker é o maior artilheiro estrangeiro da história da liga espanhola jogando pelo Real Madrid, mas antes disso já era artilheiro consagrado na antiga Iugoslávia. Quantos gols ele marcou na liga croata pelo Dínamo Zagreb?',
   150, 'gols', 'futebol', 3, 'REJEITADA — tripla premissa falsa: (1) Šuker é croata jogando pelo Dínamo Zagreb na própria liga croata/iugoslava, ou seja, não é "estrangeiro" nessa competição — foge do tema da família; (2) a Wikipedia não sustenta que ele seja o maior artilheiro estrangeiro da história de La Liga (114 gols em 239 jogos na Espanha, sem essa distinção registrada); (3) o total apurado pelo Dínamo Zagreb é 34 gols em 60 jogos (1989–91), não 150', 'rejected://suker-dinamo-nao-e-estrangeiro', 1991, 'rejected'),
  ('Quantos gols o brasileiro Rafael marcou pelo Zenit na liga russa, um dos números altos de estrangeiro na competição?',
   30, 'gols', 'futebol', 3, 'REJEITADA — sem fonte rastreável: busca exaustiva (Wikipedia em português, inglês e russo, mais mecanismos de busca) não encontrou nenhum jogador brasileiro chamado "Rafael" associado ao Zenit São Petersburgo; o artigo do clube lista Hulk, Danny, Douglas Santos e Luiz Henrique como brasileiros notáveis, sem menção a um "Rafael"', 'rejected://rafael-zenit-sem-fonte', 2010, 'rejected'),
  ('Quantos gols o brasileiro Cléo marcou na liga russa jogando por Rubin Kazan e outros clubes?',
   70, 'gols', 'futebol', 3, 'REJEITADA — sem fonte rastreável: busca exaustiva não confirmou uma passagem do atacante brasileiro Cléo pelo Rubin Kazan nem um total de gols na liga russa; a única menção localizada associa esse jogador a gols pelo FK Partizan (Sérvia), clube diferente do citado na pergunta', 'rejected://cleo-rubin-kazan-sem-fonte', 2015, 'rejected'),
  ('Quantos gols o nigeriano Rashidi Yekini marcou na liga portuguesa jogando pelo Vitória de Setúbal, clube pelo qual foi artilheiro do campeonato em 1993–94?',
   94, 'gols', 'futebol', 3, 'Wikipedia — "Rashidi Yekini" (94 gols pelo Vitória de Setúbal somando as duas passagens, 1990–94 e 1997; candidato original citava também o "Sporting", mas a Wikipedia mostra que o único clube de nome parecido em sua carreira foi o Sporting de Gijón, na Espanha — não o Sporting CP de Lisboa)', 'https://en.wikipedia.org/wiki/Rashidi_Yekini', 1997, 'approved'),

-- Família 11: público recorde do estádio do clube (maior comparecimento já registrado)
  ('Qual o maior público já registrado no Estádio da Luz, casa do Benfica, em Lisboa?',
   135000, 'pessoas', 'futebol', 3, 'Wikipedia (pt) — "Estádio da Luz (1954)", infobox: público recorde de 135.000 (SL Benfica 3–1 FC Porto, "jogo do título")', 'https://pt.wikipedia.org/wiki/Est%C3%A1dio_da_Luz_(1954)', 1987, 'approved'),
  ('Qual o maior público já registrado no Ibrox Stadium, casa do Rangers, na Escócia?',
   118567, 'pessoas', 'futebol', 3, 'Wikipedia — "Ibrox Stadium", infobox: recorde britânico de 118.567 (Rangers x Celtic, jogo de campeonato, 2 jan. 1939)', 'https://en.wikipedia.org/wiki/Ibrox_Stadium', 1939, 'approved'),
  ('Qual o maior público já registrado no Hampden Park, estádio da seleção escocesa em Glasgow?',
   149415, 'pessoas', 'futebol', 3, 'Wikipedia — "Hampden Park": público oficial de 149.415 (Escócia x Inglaterra, 17 abr. 1937), recorde europeu para jogo de seleções', 'https://en.wikipedia.org/wiki/Hampden_Park', 1937, 'approved'),
  ('Qual o maior público já registrado no antigo estádio De Meer, do Ajax, na Holanda?',
   30000, 'pessoas', 'futebol', 3, 'REJEITADA — sem fonte rastreável para um público recorde específico (Wikipedia em inglês e em holandês, e demais fontes tentadas, só citam capacidade máxima genérica de ~29.500, sem jogo/data/número de público citável)', 'rejected://sem-fonte-de-meer', 1996, 'rejected'),
  ('Qual o maior público já registrado no Estádio Marakana, casa do Estrela Vermelha, na Sérvia?',
   116000, 'pessoas', 'futebol', 3, 'Wikipedia — "Red Star Stadium", infobox: público recorde de 116.000 (Estrela Vermelha x Ferencváros, semifinal da Recopa Europeia, 23 abr. 1975)', 'https://en.wikipedia.org/wiki/Red_Star_Stadium', 1975, 'approved'),
  ('Qual o maior público já registrado no Estádio Luzhniki, em Moscou, na Rússia?',
   102538, 'pessoas', 'futebol', 3, 'Wikipedia — "Luzhniki Stadium", infobox: público recorde de 102.538 (União Soviética x Itália, 13 out. 1963)', 'https://en.wikipedia.org/wiki/Luzhniki_Stadium', 1963, 'approved'),
  ('Qual o maior público já registrado no Estádio Ali Sami Yen, antiga casa do Galatasaray, na Turquia?',
   48600, 'pessoas', 'futebol', 3, 'Wikipedia — "Ali Sami Yen Stadium", tabela de recordes de público: 48.600 (Turquia x Bulgária, jogo inaugural do estádio, 20 dez. 1964)', 'https://en.wikipedia.org/wiki/Ali_Sami_Yen_Stadium', 1964, 'approved'),
  ('Qual o maior público já registrado no Estádio Maksimir, casa do Dínamo Zagreb, na Croácia?',
   64138, 'pessoas', 'futebol', 3, 'Wikipedia — "Stadion Maksimir", infobox: público recorde de 64.138 (NK Zagreb x NK Osijek, 19 jul. 1973)', 'https://en.wikipedia.org/wiki/Stadion_Maksimir', 1973, 'approved'),
  ('Qual o maior público já registrado no Estádio Népstadion (Puskás Ferenc Stadion antigo), na Hungria?',
   104000, 'pessoas', 'futebol', 3, 'Wikipedia — "Puskás Ferenc Stadium", infobox: público recorde de 104.000 (Vasas Budapeste x Rapid Viena, 28 jul. 1956)', 'https://en.wikipedia.org/wiki/Puskás_Ferenc_Stadium', 1956, 'approved'),
  ('Qual o maior público já registrado no antigo Estádio Constant Vanden Stock, casa do Anderlecht, na Bélgica?',
   38349, 'pessoas', 'futebol', 3, 'Wikipedia — "Constant Vanden Stock Stadium": recorde de público de 38.349 (Anderlecht x Standard de Liège, 20 set. 1980), anterior às reformas de capacidade', 'https://en.wikipedia.org/wiki/Constant_Vanden_Stock_Stadium', 1980, 'approved'),

-- Família 12: idade do jogador mais jovem a estrear pelo clube na 1ª divisão
  ('Qual a idade do jogador mais jovem a estrear pelo Ajax na Eredivisie?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Sporting na Primeira Liga portuguesa?',
   15, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Celtic na liga escocesa?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Fenerbahçe na liga turca?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Club Brugge na liga belga?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Dínamo Zagreb na liga croata?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Shakhtar Donetsk na liga ucraniana?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo PSV Eindhoven na Eredivisie?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Benfica na Primeira Liga portuguesa?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Qual a idade do jogador mais jovem a estrear pelo Red Bull Salzburg na liga austríaca?',
   16, 'anos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),

-- Família 13: número de rebaixamentos já sofridos pelo clube na história (clubes tradicionais)
  ('Quantas vezes o Fenerbahçe já foi rebaixado da primeira divisão turca em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Quantas vezes o Ajax já foi rebaixado da primeira divisão holandesa em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Quantas vezes o Benfica já foi rebaixado da primeira divisão portuguesa em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Quantas vezes o Rangers já foi rebaixado da primeira divisão escocesa antes de sua reformulação financeira de 2012?',
   0, 'rebaixamentos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2012, 'pending'),
  ('Quantas vezes o Anderlecht já foi rebaixado da primeira divisão belga em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Quantas vezes o Feyenoord já foi rebaixado da primeira divisão holandesa em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Quantas vezes o Hamburgo (Alemanha) já foi rebaixado da primeira divisão antes de sua primeira queda em 2018?',
   0, 'rebaixamentos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2018, 'pending'),
  ('Quantas vezes o Sporting já foi rebaixado da primeira divisão portuguesa em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Quantas vezes o Galatasaray já foi rebaixado da primeira divisão turca em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),
  ('Quantas vezes o Celtic já foi rebaixado da primeira divisão escocesa em toda a sua história?',
   0, 'rebaixamentos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2025, 'pending'),

-- Família 14: maior goleada da história do clube num campeonato nacional
  ('Qual a maior goleada da história do Ajax num jogo da Eredivisie?',
   14, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1972, 'pending'),
  ('Qual a maior goleada da história do Benfica num jogo do Campeonato Português?',
   14, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1960, 'pending'),
  ('Qual a maior goleada da história do Celtic num jogo da liga escocesa?',
   11, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1938, 'pending'),
  ('Qual a maior goleada da história do Fenerbahçe num jogo da liga turca?',
   10, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1990, 'pending'),
  ('Qual a maior goleada da história do Estrela Vermelha num jogo da liga sérvia (ou iugoslava)?',
   10, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1975, 'pending'),
  ('Qual a maior goleada da história do Spartak Moscou num jogo da liga russa (ou soviética)?',
   9, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1978, 'pending'),
  ('Qual a maior goleada da história do PSV Eindhoven num jogo da Eredivisie?',
   11, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1965, 'pending'),
  ('Qual a maior goleada da história do Rangers num jogo da liga escocesa?',
   14, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1899, 'pending'),
  ('Qual a maior goleada da história do Dínamo Kiev num jogo do campeonato soviético (ou ucraniano)?',
   9, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1974, 'pending'),
  ('Qual a maior goleada da história do Porto num jogo do Campeonato Português?',
   12, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1975, 'pending');
