-- RASCUNHO NÃO VERIFICADO. Todas as ~140 linhas abaixo foram escritas de memória, sem pesquisa
-- (sem WebSearch/WebFetch) — é geração de volume de candidatos, não curadoria. Todo `answer` é
-- estimativa educada; toda `source_name`/`source_url` é placeholder. status = 'pending' em toda
-- linha; start_round só sorteia status = 'approved', então nada aqui entra em partida real antes
-- de uma sessão futura confirmar cada número com fonte real e decidir aprovar/rejeitar (mesmo
-- processo usado no início do banco, ver cabeçalho de futebol_01.sql).
--
-- Foco: seleções, clubes e ligas domésticas da ÁFRICA, ÁSIA e CONCACAF — Nigéria, Gana, Egito,
-- Marrocos, Senegal, Camarões, Costa do Marfim, África do Sul, Argélia, Tunísia; Japão, Coreia do
-- Sul, China, Arábia Saudita, Irã, Catar, Austrália; México, Estados Unidos, Costa Rica, Jamaica,
-- Honduras.
--
-- Famílias incluídas (cada uma cobre 1 métrica, variando o clube/seleção/país):
--   1.  Artilheiro histórico do clube (maior goleador de sempre)
--   2.  Clube com mais títulos da liga nacional — por país
--   3.  Ano de fundação do clube
--   4.  Capacidade do estádio do clube
--   5.  Jogador com mais jogos pela seleção nacional (recordista de partidas)
--   6.  Maior artilheiro histórico da seleção nacional
--   7.  Participações em Copa Africana das Nações / Copa da Ásia por seleção
--   8.  Melhor posição já alcançada no ranking FIFA por seleção
--   9.  Ano de fundação da federação nacional de futebol
--   10. Maior goleada da história da seleção nacional (gols de diferença)
--   11. Transferência de saída mais cara envolvendo jogador do país
--   12. Participações em Copa do Mundo por seleção
--   13. Ano do último título de campeonato continental de seleções (CAN / Copa da Ásia)
--   14. Clube mais titulado do país na competição continental de clubes (Liga dos Campeões da
--       CAF / Liga dos Campeões da AFC)

insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values

-- Família 1: artilheiro histórico do clube (maior goleador de sempre)
  ('O Al Ahly é o clube mais titulado da história do futebol egípcio e africano. Quantos gols marcou Taher Abouzaid, um dos maiores artilheiros da história do clube?',
   120, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1985, 'pending'),
  ('O Zamalek é o principal rival do Al Ahly no Cairo. Quantos gols marcou Mahmoud El-Khatib, apelidado de "Bibo", maior artilheiro da história do clube?',
   200, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1990, 'pending'),
  ('O Raja Casablanca é um dos clubes mais populares de Marrocos. Quantos gols marcou Mustapha Choukri, um dos maiores artilheiros da história do clube?',
   90, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1985, 'pending'),
  ('O Kaizer Chiefs é um dos clubes mais populares da África do Sul. Quantos gols marcou Marks Maponyane, um dos maiores artilheiros da história do clube?',
   150, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1990, 'pending'),
  ('O Al Hilal é o clube mais titulado da Arábia Saudita. Quantos gols marcou Majed Abdullah, o maior artilheiro da história do clube?',
   155, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1994, 'pending'),
  ('O Jeonbuk Hyundai Motors é um dos clubes mais vitoriosos da Coreia do Sul. Quantos gols marcou Lee Dong-gook, o maior artilheiro da história do clube?',
   137, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('O Club América é um dos clubes mais populares do México. Quantos gols marcou Cuauhtémoc Blanco pelo clube ao longo da carreira?',
   180, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('O Cruz Azul é um dos clubes tradicionais do futebol mexicano. Quantos gols marcou Carlos Hermosillo, um dos maiores artilheiros da história do clube?',
   180, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1998, 'pending'),
  ('O Deportivo Saprissa é o clube mais popular da Costa Rica. Quantos gols marcou Rónald Gómez, um dos maiores artilheiros da história do clube?',
   130, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('O Urawa Red Diamonds é um dos clubes mais populares do futebol japonês. Quantos gols marcou Emerson, um dos maiores artilheiros estrangeiros da história do clube?',
   50, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2007, 'pending'),

-- Família 2: clube com mais títulos da liga nacional, por país
  ('No Egito, o Al Ahly é disparado o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   44, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Em Marrocos, o Wydad Casablanca é um dos maiores campeões da liga nacional. Quantos títulos ele já venceu, ao todo?',
   22, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Na Tunísia, o Espérance de Tunis é o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   32, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Na África do Sul, o Kaizer Chiefs é um dos clubes mais vitoriosos da história da liga nacional. Quantos títulos ele já venceu, ao todo, somando todas as eras do campeonato?',
   21, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Na Arábia Saudita, o Al Hilal é disparado o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   19, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('No Japão, o Kashima Antlers é o maior campeão da era profissional da liga nacional (J.League). Quantos títulos ele já venceu, ao todo?',
   8, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Na Coreia do Sul, o Jeonbuk Hyundai Motors é um dos maiores campeões da liga nacional (K League). Quantos títulos ele já venceu, ao todo?',
   9, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('No México, o Club América é um dos maiores campeões da liga nacional. Quantos títulos ele já venceu, ao todo?',
   13, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Na Costa Rica, o Deportivo Saprissa é disparado o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   36, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Em Honduras, o Olimpia é disparado o maior campeão da liga nacional. Quantos títulos ele já venceu, ao todo?',
   34, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

-- Família 3: ano de fundação do clube
  ('Em que ano foi fundado o Al Ahly, o clube mais titulado da história do futebol africano?',
   1907, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1907, 'pending'),
  ('Em que ano foi fundado o Zamalek, rival histórico do Al Ahly no Cairo?',
   1911, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1911, 'pending'),
  ('Em que ano foi fundado o Raja Casablanca, um dos clubes mais populares de Marrocos?',
   1949, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1949, 'pending'),
  ('Em que ano foi fundado o Wydad Casablanca, rival histórico do Raja em Marrocos?',
   1937, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1937, 'pending'),
  ('Em que ano foi fundado o Espérance de Tunis, o clube mais tradicional da Tunísia?',
   1919, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1919, 'pending'),
  ('Em que ano foi fundado o Kaizer Chiefs, um dos clubes mais populares da África do Sul?',
   1970, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1970, 'pending'),
  ('Em que ano foi fundado o Al Hilal, o clube mais titulado da Arábia Saudita?',
   1957, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1957, 'pending'),
  ('Em que ano foi fundado o Club América, um dos clubes mais populares do México?',
   1916, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1916, 'pending'),
  ('Em que ano foi fundado o Cruz Azul, um dos clubes tradicionais do futebol mexicano?',
   1927, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1927, 'pending'),
  ('Em que ano foi fundado o Deportivo Saprissa, o clube mais popular da Costa Rica?',
   1930, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1930, 'pending'),

-- Família 4: capacidade do estádio do clube
  ('Qual a capacidade do Cairo International Stadium, onde o Al Ahly manda parte de seus jogos?',
   75000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Complexo Mohammed V, em Casablanca, onde o Raja manda seus jogos?',
   45000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do FNB Stadium, em Johanesburgo, palco de jogos do Kaizer Chiefs e da final da Copa de 2010?',
   94000, 'lugares', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do King Fahd International Stadium, em Riad, onde o Al Hilal manda parte de seus jogos?',
   68000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Azteca, casa do Club América e palco de duas finais de Copa do Mundo?',
   87000, 'lugares', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do estádio do Cruz Azul, na Cidade do México?',
   33000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Estádio Ricardo Saprissa, casa do Deportivo Saprissa, na Costa Rica?',
   23000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Jeonju World Cup Stadium, casa do Jeonbuk Hyundai Motors, na Coreia do Sul?',
   42000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do Saitama Stadium 2002, casa do Urawa Red Diamonds, no Japão?',
   63700, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual a capacidade do estádio do Zamalek, no Cairo?',
   30000, 'lugares', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

-- Família 5: jogador com mais jogos pela seleção nacional (recordista de partidas)
  ('Joseph Yobo é o jogador com mais partidas pela seleção nigeriana. Quantos jogos ele disputou pela Nigéria?',
   101, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('Asamoah Gyan é um dos jogadores com mais partidas pela seleção ganesa. Quantos jogos ele disputou por Gana?',
   109, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Ahmed Hassan é um dos jogadores com mais partidas pela seleção egípcia, e um dos recordistas de todo o continente africano. Quantos jogos ele disputou pelo Egito?',
   184, 'jogos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2012, 'pending'),
  ('Noureddine Naybet é um dos jogadores com mais partidas pela seleção marroquina. Quantos jogos ele disputou por Marrocos?',
   115, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2005, 'pending'),
  ('Kalidou Koulibaly é um dos jogadores com mais partidas pela seleção senegalesa. Quantos jogos ele já disputou pelo Senegal?',
   100, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Yasuhito Endo é o jogador com mais partidas pela seleção japonesa. Quantos jogos ele disputou pelo Japão?',
   152, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Hong Myung-bo é um dos jogadores com mais partidas pela seleção sul-coreana. Quantos jogos ele disputou pela Coreia do Sul?',
   136, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2002, 'pending'),
  ('Andrés Guardado é o jogador com mais partidas pela seleção mexicana. Quantos jogos ele disputou pelo México?',
   180, 'jogos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Cobi Jones é o jogador com mais partidas pela seleção dos Estados Unidos. Quantos jogos ele disputou pelos EUA?',
   164, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2004, 'pending'),
  ('Keylor Navas é um dos jogadores com mais partidas pela seleção costarriquenha. Quantos jogos ele já disputou pela Costa Rica?',
   118, 'jogos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),

-- Família 6: maior artilheiro histórico da seleção nacional
  ('Rashidi Yekini é um dos maiores artilheiros da história da seleção nigeriana. Quantos gols ele marcou pela Nigéria?',
   37, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1998, 'pending'),
  ('Asamoah Gyan é o maior artilheiro da história da seleção ganesa. Quantos gols ele marcou por Gana?',
   51, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Hossam Hassan é o maior artilheiro da história da seleção egípcia. Quantos gols ele marcou pelo Egito?',
   68, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2006, 'pending'),
  ('Samuel Eto''o é o maior artilheiro da história da seleção camaronesa. Quantos gols ele marcou pelos Camarões?',
   56, 'gols', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('Didier Drogba é o maior artilheiro da história da seleção marfinense. Quantos gols ele marcou pela Costa do Marfim?',
   65, 'gols', 'futebol', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('Sadio Mané é o maior artilheiro da história da seleção senegalesa. Quantos gols ele já marcou pelo Senegal?',
   44, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Kunishige Kamamoto é o maior artilheiro da história da seleção japonesa, recorde que resiste desde os anos 1970. Quantos gols ele marcou pelo Japão?',
   75, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1977, 'pending'),
  ('Cha Bum-kun é um dos maiores artilheiros da história da seleção sul-coreana. Quantos gols ele marcou pela Coreia do Sul?',
   58, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1986, 'pending'),
  ('Javier "Chicharito" Hernández é o maior artilheiro da história da seleção mexicana. Quantos gols ele marcou pelo México?',
   52, 'gols', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Clint Dempsey é um dos maiores artilheiros da história da seleção dos Estados Unidos. Quantos gols ele marcou pelos EUA?',
   57, 'gols', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),

-- Família 7: participações em Copa Africana das Nações / Copa da Ásia por seleção
  ('Quantas edições da Copa Africana das Nações a Nigéria já disputou, ao todo, contando até 2023?',
   19, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Gana é uma das seleções mais frequentes na Copa Africana das Nações. Quantas edições ela já disputou, ao todo, contando até 2023?',
   23, 'participações', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Egito é a seleção com mais participações na história da Copa Africana das Nações. Quantas edições ele já disputou, ao todo?',
   26, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Quantas edições da Copa Africana das Nações os Camarões já disputaram, ao todo, contando até 2023?',
   20, 'participações', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Quantas edições da Copa Africana das Nações Marrocos já disputou, ao todo, contando até 2023?',
   18, 'participações', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Quantas edições da Copa da Ásia o Japão já disputou, ao todo, contando até 2023?',
   10, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('A Coreia do Sul é uma das seleções com mais participações na história da Copa da Ásia. Quantas edições ela já disputou, ao todo?',
   15, 'participações', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Quantas edições da Copa da Ásia a Arábia Saudita já disputou, ao todo, contando até 2023?',
   11, 'participações', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Quantas edições da Copa da Ásia o Irã já disputou, ao todo, contando até 2023?',
   15, 'participações', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('A Austrália ingressou na confederação asiática de futebol (AFC) em 2006. Quantas edições da Copa da Ásia ela já disputou desde então, contando até 2023?',
   5, 'participações', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),

-- Família 8: melhor posição já alcançada no ranking FIFA por seleção
  ('A Nigéria teve seu auge no futebol mundial nos anos 1990. Qual a melhor posição que ela já alcançou no ranking da FIFA?',
   5, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1994, 'pending'),
  ('Os Camarões chegaram a ser uma potência africana no ranking da FIFA. Qual a melhor posição que a seleção já alcançou?',
   11, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1993, 'pending'),
  ('O Senegal viveu seu auge recente com uma geração vitoriosa. Qual a melhor posição que a seleção já alcançou no ranking da FIFA?',
   18, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('O México é uma das seleções mais estáveis do ranking da FIFA. Qual a melhor posição que ele já alcançou?',
   4, 'posição', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1998, 'pending'),
  ('Os Estados Unidos chegaram perto do topo do ranking da FIFA em meados dos anos 2000. Qual a melhor posição que a seleção já alcançou?',
   4, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2006, 'pending'),
  ('A Coreia do Sul teve seu auge no ranking da FIFA após o histórico quarto lugar na Copa de 2002. Qual a melhor posição que ela já alcançou?',
   17, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2002, 'pending'),
  ('O Japão é uma das seleções mais estáveis da Ásia no ranking da FIFA. Qual a melhor posição que ele já alcançou?',
   9, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2013, 'pending'),
  ('A Arábia Saudita teve seu auge no ranking da FIFA após um bom desempenho na Copa de 1998. Qual a melhor posição que a seleção já alcançou?',
   21, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1998, 'pending'),
  ('A Costa Rica teve seu auge no ranking da FIFA após chegar às quartas de final da Copa de 2014. Qual a melhor posição que a seleção já alcançou?',
   15, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('Gana teve seu auge no ranking da FIFA após chegar às quartas de final da Copa de 2010. Qual a melhor posição que a seleção já alcançou?',
   14, 'posição', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),

-- Família 9: ano de fundação da federação nacional de futebol
  ('Em que ano foi fundada a federação de futebol do Egito, uma das primeiras do continente africano?',
   1921, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1921, 'pending'),
  ('Em que ano foi fundada a federação de futebol da Nigéria?',
   1945, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1945, 'pending'),
  ('Em que ano foi fundada a federação de futebol de Gana?',
   1957, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1957, 'pending'),
  ('Em que ano foi fundada a federação de futebol de Marrocos?',
   1955, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1955, 'pending'),
  ('Em que ano foi fundada a federação de futebol do Senegal?',
   1960, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1960, 'pending'),
  ('Em que ano foi fundada a federação de futebol do México?',
   1927, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1927, 'pending'),
  ('Em que ano foi fundada a federação de futebol dos Estados Unidos, uma das mais antigas do mundo fora da Europa?',
   1913, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1913, 'pending'),
  ('Em que ano foi fundada a federação de futebol do Japão?',
   1921, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1921, 'pending'),
  ('Em que ano foi fundada a federação de futebol da Coreia do Sul?',
   1928, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1928, 'pending'),
  ('Em que ano foi fundada a federação de futebol da Costa Rica?',
   1921, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1921, 'pending'),

-- Família 10: maior goleada da história da seleção nacional (gols de diferença)
  ('Qual a maior goleada da história da seleção nigeriana, em número de gols de diferença?',
   10, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2005, 'pending'),
  ('O México já aplicou goleadas históricas em seleções menores do Caribe. Qual a maior goleada da história da seleção mexicana, em gols de diferença?',
   11, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2012, 'pending'),
  ('Qual a maior goleada da história da seleção dos Estados Unidos, em gols de diferença?',
   11, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2007, 'pending'),
  ('Em 2003, a Coreia do Sul aplicou uma das maiores goleadas de sua história sobre o Nepal. Qual foi a diferença de gols nessa partida?',
   16, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2003, 'pending'),
  ('Em 2000, o Irã goleou o Guam por 19 a 0 nas eliminatórias, uma das maiores goleadas já registradas em jogos oficiais de seleções. Qual foi a diferença de gols nessa partida?',
   19, 'gols de diferença', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2000, 'pending'),
  ('Em 2001, a Austrália goleou a Samoa Americana por 31 a 0 nas eliminatórias, a maior goleada já registrada na história do futebol entre seleções. Qual foi a diferença de gols nessa partida?',
   31, 'gols de diferença', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2001, 'pending'),
  ('Qual a maior goleada da história da seleção japonesa, em gols de diferença?',
   15, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2000, 'pending'),
  ('Qual a maior goleada da história da seleção saudita, em gols de diferença?',
   10, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Qual a maior goleada da história da seleção costarriquenha, em gols de diferença?',
   9, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2011, 'pending'),
  ('Qual a maior goleada da história da seleção camaronesa, em gols de diferença?',
   10, 'gols de diferença', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2001, 'pending'),

-- Família 11: transferência de saída mais cara envolvendo jogador do país
  ('Mohamed Salah saiu da Roma rumo ao Liverpool em 2017, num negócio que se tornou a transferência mais cara já envolvendo um jogador egípcio. Por quantos milhões de euros ele foi negociado?',
   42, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2017, 'pending'),
  ('Kalidou Koulibaly saiu do Napoli rumo ao Chelsea em 2022, num dos negócios mais caros já envolvendo um jogador senegalês. Por quantos milhões de euros ele foi negociado?',
   38, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Achraf Hakimi saiu da Internazionale rumo ao PSG em 2021, na transferência mais cara já envolvendo um jogador marroquino. Por quantos milhões de euros ele foi negociado?',
   60, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2021, 'pending'),
  ('Victor Osimhen saiu do Lille rumo ao Napoli em 2020, na transferência mais cara já envolvendo um jogador nigeriano. Por quantos milhões de euros ele foi negociado?',
   70, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('André Onana saiu da Internazionale rumo ao Manchester United em 2023, na transferência mais cara já envolvendo um goleiro camaronês. Por quantos milhões de euros ele foi negociado?',
   50, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('Nicolas Pépé saiu do Lille rumo ao Arsenal em 2019, na transferência mais cara já envolvendo um jogador marfinense. Por quantos milhões de euros ele foi negociado?',
   80, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Shinji Kagawa saiu do Borussia Dortmund rumo ao Manchester United em 2012, num dos negócios mais caros já envolvendo um jogador japonês. Por quantos milhões de euros ele foi negociado?',
   17, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2012, 'pending'),
  ('Son Heung-min saiu do Bayer Leverkusen rumo ao Tottenham em 2015, na transferência mais cara já envolvendo um jogador sul-coreano. Por quantos milhões de euros ele foi negociado?',
   30, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Hirving Lozano saiu do PSV rumo ao Napoli em 2019, num dos negócios mais caros já envolvendo um jogador mexicano. Por quantos milhões de euros ele foi negociado?',
   38, 'milhões de euros', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Christian Pulisic saiu do Borussia Dortmund rumo ao Chelsea em 2019, na transferência mais cara já envolvendo um jogador norte-americano. Por quantos milhões de euros ele foi negociado?',
   64, 'milhões de euros', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),

-- Família 12: participações em Copa do Mundo por seleção
  ('Quantas Copas do Mundo o México já disputou, ao todo, sendo um dos países com mais participações?',
   17, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo os Estados Unidos já disputaram, ao todo, contando até 2022?',
   11, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo a Costa Rica já disputou, ao todo, contando até 2022?',
   6, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('A Jamaica se classificou para uma única Copa do Mundo em toda sua história, em 1998. Quantas participações ela tem, ao todo?',
   1, 'participação', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1998, 'pending'),
  ('Quantas Copas do Mundo Honduras já disputou, ao todo, contando até 2014?',
   3, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('Quantas Copas do Mundo a Coreia do Sul já disputou, ao todo, contando até 2022?',
   11, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo o Japão já disputou, ao todo, contando até 2022?',
   7, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo a Arábia Saudita já disputou, ao todo, contando até 2022?',
   6, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo o Irã já disputou, ao todo, contando até 2022?',
   6, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Quantas Copas do Mundo os Camarões já disputaram, ao todo, sendo uma das seleções africanas mais frequentes no torneio, contando até 2022?',
   8, 'participações', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),

-- Família 13: ano do último título de campeonato continental de seleções (CAN / Copa da Ásia)
  ('Em que ano a Nigéria venceu sua última Copa Africana das Nações?',
   2013, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2013, 'pending'),
  ('Gana é uma das seleções mais tradicionais da África, mas vive um jejum enorme na Copa Africana das Nações. Em que ano foi o último título ganês?',
   1982, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1982, 'pending'),
  ('Em que ano os Camarões venceram sua última Copa Africana das Nações?',
   2017, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2017, 'pending'),
  ('Em que ano o Egito venceu sua última Copa Africana das Nações, mantendo o recorde de mais títulos do torneio?',
   2010, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2010, 'pending'),
  ('A África do Sul venceu sua única Copa Africana das Nações jogando em casa. Em que ano foi esse título?',
   1996, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1996, 'pending'),
  ('Em que ano o Japão venceu sua última Copa da Ásia?',
   2011, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2011, 'pending'),
  ('Em que ano a Arábia Saudita venceu sua última Copa da Ásia?',
   1996, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1996, 'pending'),
  ('O Irã é uma potência histórica do futebol asiático, mas vive um jejum enorme na Copa da Ásia. Em que ano foi o último título iraniano?',
   1976, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1976, 'pending'),
  ('A Coreia do Sul tem um dos jejuns mais longos e comentados do futebol asiático na Copa da Ásia. Em que ano foi o último título sul-coreano?',
   1960, 'ano', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1960, 'pending'),
  ('A Austrália venceu sua única Copa da Ásia jogando em casa. Em que ano foi esse título?',
   2015, 'ano', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),

-- Família 14: clube mais titulado do país na competição continental de clubes (Liga dos Campeões da CAF / AFC)
  ('O Al Ahly é o clube com mais títulos da história da Liga dos Campeões da CAF, a principal competição de clubes da África. Quantos títulos ele já venceu?',
   12, 'títulos', 'futebol', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Espérance de Tunis é o clube tunisiano mais titulado da Liga dos Campeões da CAF. Quantos títulos ele já venceu?',
   4, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('O Wydad Casablanca é o clube marroquino mais titulado da Liga dos Campeões da CAF. Quantos títulos ele já venceu?',
   3, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('O TP Mazembe, da República Democrática do Congo, é um dos clubes mais titulados da Liga dos Campeões da CAF. Quantos títulos ele já venceu?',
   5, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('O Canon Yaoundé é o clube camaronês mais titulado da Liga dos Campeões da CAF. Quantas vezes ele já venceu o torneio?',
   1, 'título', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1980, 'pending'),
  ('O Al Hilal é o clube saudita mais titulado da Liga dos Campeões da AFC, a principal competição de clubes da Ásia. Quantos títulos ele já venceu?',
   4, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2021, 'pending'),
  ('O Urawa Red Diamonds é um dos clubes japoneses mais titulados da Liga dos Campeões da AFC. Quantos títulos ele já venceu?',
   2, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('O Pohang Steelers é o clube sul-coreano com mais títulos da Liga dos Campeões da AFC. Quantos títulos ele já venceu?',
   3, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2009, 'pending'),
  ('Apesar de duas finais disputadas, nenhum clube iraniano jamais venceu a Liga dos Campeões da AFC. Quantas vezes o Persépolis, principal candidato do país, já foi campeão?',
   0, 'títulos', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Al Sadd é o clube catariano mais titulado da Liga dos Campeões da AFC. Quantas vezes ele já venceu o torneio?',
   1, 'título', 'futebol', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2011, 'pending');
