-- Onda de aprovação 2/7 do tópico futebol — status 'pending', mesmas regras do arquivo 01
-- (ver cabeçalho de futebol_01.sql e o plano em
-- C:\Users\gianf\.claude\plans\agora-que-ja-temos-snuggly-kazoo.md).

-- Família: rebaixamentos para a Série B na história de clubes brasileiros tradicionais.
insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values
  ('O Botafogo, campeão brasileiro em 1995, já foi rebaixado para a Série B quantas vezes na história?',
   3, 'rebaixamentos', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Vasco, um dos clubes mais tradicionais do Rio, já foi rebaixado para a Série B quantas vezes na história?',
   3, 'rebaixamentos', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Fluminense, tricampeão carioca recente, já foi rebaixado para a Série B quantas vezes na história?',
   3, 'rebaixamentos', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Cruzeiro, apesar de duas décadas vitoriosas, já foi rebaixado para a Série B quantas vezes na história?',
   2, 'rebaixamentos', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Grêmio, tricampeão da Libertadores, já foi rebaixado para a Série B quantas vezes na história?',
   2, 'rebaixamentos', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Internacional, um dos clubes mais estáveis do Sul, já foi rebaixado para a Série B quantas vezes na história?',
   1, 'rebaixamentos', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Atlético-MG, campeão da Libertadores em 2013, já foi rebaixado para a Série B quantas vezes na história?',
   1, 'rebaixamentos', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Bahia, tricampeão brasileiro nas décadas de 1950 e 1980, já foi rebaixado para a Série B quantas vezes na história?',
   4, 'rebaixamentos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Sport, campeão da Copa do Brasil em 2008, já foi rebaixado para a Série B quantas vezes na história?',
   5, 'rebaixamentos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Coritiba, um dos clubes mais antigos do Brasil, já foi rebaixado para a Série B quantas vezes na história?',
   6, 'rebaixamentos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending');

-- Família: pênaltis perdidos na carreira profissional (todas as competições), por jogador.
insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values
  ('Neymar é um dos principais cobradores de pênalti do futebol brasileiro. Quantos pênaltis ele já perdeu na carreira profissional?',
   12, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Hulk é conhecido pela cobrança forte de pênaltis. Quantos ele já perdeu na carreira profissional?',
   9, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Gabigol é um dos artilheiros do futebol brasileiro recente. Quantos pênaltis ele já perdeu na carreira profissional?',
   8, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Deyverson, atacante conhecido pelas comemorações, quantos pênaltis já perdeu na carreira profissional?',
   6, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Jô, artilheiro que rodou por Corinthians e outros clubes, quantos pênaltis já perdeu na carreira profissional?',
   7, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Diego Costa, atacante que defendeu Brasil e Espanha, quantos pênaltis já perdeu na carreira profissional?',
   5, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Fred, artilheiro histórico do Fluminense, quantos pênaltis já perdeu na carreira profissional?',
   10, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Diego Tardelli, atacante que rodou por vários clubes grandes, quantos pênaltis já perdeu na carreira profissional?',
   6, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Robinho, um dos maiores talentos do futebol brasileiro dos anos 2000, quantos pênaltis já perdeu na carreira profissional?',
   4, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Ricardo Oliveira, artilheiro que marcou por vários clubes na Série A, quantos pênaltis já perdeu na carreira profissional?',
   5, 'pênaltis perdidos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending');

-- Família: número de sócios-torcedores de clubes brasileiros (ano de referência 2023).
insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values
  ('O Flamengo tem o maior programa de sócio-torcedor do Brasil. Quantos sócios o clube tinha em 2023?',
   190000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Corinthians tem uma das maiores torcidas organizadas do país. Quantos sócios-torcedores o clube tinha em 2023?',
   150000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Internacional tem tradição em programas de sócio-torcedor no Sul do país. Quantos sócios o clube tinha em 2023?',
   130000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Grêmio disputa com o rival gaúcho o maior número de sócios do Sul. Quantos sócios-torcedores o clube tinha em 2023?',
   130000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O São Paulo tem um dos programas de sócio-torcedor mais antigos do país. Quantos sócios o clube tinha em 2023?',
   140000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Palmeiras vive fase vitoriosa e viu o programa de sócios crescer. Quantos sócios-torcedores o clube tinha em 2023?',
   130000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Atlético-MG lançou a Arena MRV apoiado em receita de sócios. Quantos sócios-torcedores o clube tinha em 2023?',
   100000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Cruzeiro reconstruiu sua base de sócios após a crise financeira do final da década de 2010. Quantos sócios o clube tinha em 2023?',
   90000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Vasco renovou sua base de sócios-torcedores nos últimos anos. Quantos sócios o clube tinha em 2023?',
   80000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('O Botafogo viu sua base de sócios crescer com a chegada de John Textor. Quantos sócios-torcedores o clube tinha em 2023?',
   70000, 'sócios-torcedores', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending');

-- Família: capacidade oficial de estádios brasileiros.
insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values
  ('Qual é a capacidade oficial do Maracanã, no Rio de Janeiro, após as reformas para a Copa de 2014?',
   78838, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial do Mineirão, em Belo Horizonte?',
   61846, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial do Beira-Rio, estádio do Internacional em Porto Alegre?',
   50128, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial da Neo Química Arena, do Corinthians, em São Paulo?',
   49205, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial do Allianz Parque, estádio do Palmeiras em São Paulo?',
   43713, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial da Arena Fonte Nova, em Salvador, casa do Bahia?',
   47907, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial da Ligga Arena (antiga Arena da Baixada), do Athletico-PR, em Curitiba?',
   42372, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial do estádio Mangueirão, em Belém, usado por Paysandu e Remo?',
   45845, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial da Vila Belmiro, estádio histórico do Santos?',
   16068, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Qual é a capacidade oficial do Couto Pereira, estádio do Coritiba?',
   40502, 'lugares', 'futebol', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending');

-- Família: tempo médio de bola rolando (minutos efetivos) por partida no Brasileirão, segundo
-- levantamentos de desempenho por edição.
insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2014?',
   52, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2014, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2015?',
   53, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2015, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2016?',
   51, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2016, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2017?',
   54, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2017, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2018?',
   55, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2018, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2019?',
   53, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2019, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2020?',
   56, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2021?',
   54, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2021, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2022?',
   55, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2022, 'pending'),
  ('Segundo levantamentos de tempo de bola em jogo, quantos minutos, em média, a bola ficou rolando por partida no Brasileirão de 2023?',
   53, 'minutos', 'futebol', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending');
