-- Lote 2 do tópico geografia — ~100 perguntas CANDIDATAS, escritas de memória (sem pesquisa),
-- organizadas em 10 famílias de ~10 perguntas cada, mesma métrica por família e sujeito
-- diferente, cobrindo Brasil e várias regiões do mundo. Todas nascem 'status = pending' com
-- source_name/source_url placeholder — uma sessão futura de curadoria (agent curador-perguntas)
-- valida número, fonte e o critério "divertida" antes de promover a 'approved'. Mesmo processo
-- já usado em supabase/seeds/futebol_25.sql.
--
-- Famílias:
-- 1. Rios do mundo — comprimento total (km)
-- 2. Ilhas — área (km²)
-- 3. Montanhas — altitude do ponto mais alto (metros)
-- 4. Lagos — área (km²)
-- 5. Litoral — extensão de costa (km)
-- 6. População — habitantes de lugares pouco óbvios (cidades, territórios, microestados)
-- 7. Densidade demográfica — habitantes por km²
-- 8. Fusos horários — quantidade oficial por país, contando territórios
-- 9. Extensão territorial — área de países/estados (km²)
-- 10. Temperatura — recordes e amplitude térmica (°C)
--
-- Não repete fato-base nem molde das perguntas já aprovadas em geografia_01.sql (Grande Muralha,
-- Deserto Antártico, estados brasileiros sem litoral, fronteiras da Rússia, altitude de La Paz)
-- nem das do seed.sql original (Challenger Deep, distância Macapá–Passo Fundo).
insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values
  -- Família 1: Rios do mundo — comprimento total (km)
  ('O Rio Yangtzé é o mais longo da Ásia e corta a China inteira de oeste a leste, da meseta tibetana até Xangai. Qual é a extensão total dele, em km?',
   6300, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Mekong nasce no planalto tibetano e atravessa seis países do sudeste asiático antes de chegar ao mar, no Vietnã. Qual é a extensão total dele, em km?',
   4350, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Danúbio é o único grande rio europeu que corre de oeste para leste, atravessando dez países até o Mar Negro. Qual é a extensão total dele, em km?',
   2850, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Volga nasce perto de Moscou e é o maior rio inteiramente europeu, desaguando no Mar Cáspio. Qual é a extensão total dele, em km?',
   3530, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio São Francisco é o único grande rio brasileiro que nasce fora e corre inteiramente dentro do semiárido nordestino, sendo apelidado de "Velho Chico". Qual é a extensão total dele, em km?',
   2830, 'km', 'geografia', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Reno nasce nos Alpes suíços e é uma das principais rotas de navegação de carga da Europa, cortando quatro países. Qual é a extensão total dele, em km?',
   1230, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Tapajós é um dos maiores afluentes do Amazonas, famoso pelas águas de um azul bem distinto do rio principal, barrento. Qual é a extensão total dele, em km?',
   2050, 'km', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Ienissei nasce na Mongólia e deságua no Oceano Ártico, sendo um dos rios mais caudalosos do planeta. Qual é a extensão total dele, em km?',
   3487, 'km', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Orinoco nasce numa serra na fronteira entre Venezuela e Brasil e forma boa parte da fronteira entre Venezuela e Colômbia. Qual é a extensão total dele, em km?',
   2140, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Rio Murray é o mais longo da Austrália, um continente conhecido pela escassez de rios grandes e permanentes. Qual é a extensão total dele, em km?',
   2508, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 2: Ilhas — área (km²)
  ('A Ilha de Baffin fica no Ártico canadense, é a quinta maior ilha do mundo e tem menos de 15 mil moradores. Qual é a área total dela, em km²?',
   507451, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Sumatra, na Indonésia, é uma das cinco Grandes Ilhas de Sonda e sozinha tem mais gente que a maioria dos países da Europa. Qual é a área total dela, em km²?',
   473481, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Ilha Vitória, no Ártico canadense, é dividida entre dois territórios do país e quase desabitada. Qual é a área total dela, em km²?',
   217291, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Ilha de Marajó, na foz do Rio Amazonas, é considerada a maior ilha fluviomarinha do mundo. Qual é a área total dela, em km²?',
   40100, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Ilha de Sacalina fica no extremo oriente russo, separada do continente por um estreito raso e congelado boa parte do ano. Qual é a área total dela, em km²?',
   72492, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Ilha Banks, no Ártico canadense, tem menos de 200 moradores permanentes espalhados por um território enorme. Qual é a área total dela, em km²?',
   70028, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Tasmânia é o estado insular da Austrália, separado do continente pelo Estreito de Bass. Qual é a área total dela, em km²?',
   64519, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Ilha do Bananal, no Tocantins, é cercada só por rios e considerada a maior ilha fluvial do mundo. Qual é a área total dela, em km²?',
   19162, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Ilha Devon, no Ártico canadense, é considerada a maior ilha desabitada do planeta — a NASA já testou equipamento lá por ela lembrar Marte. Qual é a área total dela, em km²?',
   55247, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Creta é a maior ilha da Grécia e berço da civilização minoica, uma das mais antigas da Europa. Qual é a área total dela, em km²?',
   8336, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 3: Montanhas — altitude do ponto mais alto (metros)
  ('O Aconcágua, na Argentina, é o pico mais alto de todo o hemisfério ocidental — Américas, Europa e tudo mais fora da Ásia. Qual é a altitude dele, em metros?',
   6961, 'metros', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Denali, no Alasca, é o pico mais alto da América do Norte, mesmo ficando bem mais ao norte que os Andes. Qual é a altitude dele, em metros?',
   6190, 'metros', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Kilimanjaro, na Tanzânia, é o ponto mais alto da África — um vulcão isolado, sem nenhuma cadeia de montanhas ao redor. Qual é a altitude dele, em metros?',
   5895, 'metros', 'geografia', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Monte Elbrus, no Cáucaso russo, é considerado o ponto mais alto da Europa — mais alto que qualquer pico dos Alpes. Qual é a altitude dele, em metros?',
   5642, 'metros', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Maciço Vinson é o ponto mais alto da Antártida, um continente inteiramente coberto de gelo. Qual é a altitude dele, em metros?',
   4892, 'metros', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Pico da Neblina, no Amazonas, é o ponto mais alto do Brasil e fica encoberto por nuvens boa parte do ano. Qual é a altitude dele, em metros?',
   2995, 'metros', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Pico Bolívar, na Venezuela, é o ponto mais alto do país e já teve uma das últimas geleiras tropicais do mundo, hoje quase extinta. Qual é a altitude dele, em metros?',
   4978, 'metros', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Puncak Jaya, na Indonésia, é o ponto mais alto da Oceania e tem neve permanente apesar de ficar a poucos graus do equador. Qual é a altitude dele, em metros?',
   4884, 'metros', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Mont Blanc, na fronteira entre França e Itália, é o ponto mais alto dos Alpes. Qual é a altitude dele, em metros?',
   4809, 'metros', 'geografia', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Pico Cristóbal Colón, na Colômbia, é o ponto mais alto do país e fica a menos de 50 km do Mar do Caribe — a montanha costeira mais alta do mundo. Qual é a altitude dele, em metros?',
   5730, 'metros', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 4: Lagos — área (km²)
  ('O Lago Baikal, na Sibéria, é o lago mais profundo do mundo e guarda sozinho cerca de 20% de toda a água doce líquida do planeta. Qual é a área total dele, em km²?',
   31722, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Lago Vitória, na fronteira entre Quênia, Uganda e Tanzânia, é o maior lago tropical do mundo. Qual é a área total dele, em km²?',
   68870, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Lago Titicaca, na fronteira entre Peru e Bolívia, é considerado o lago navegável mais alto do mundo. Qual é a área total dele, em km²?',
   8372, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Mar Cáspio, entre a Europa e a Ásia, é tecnicamente um lago (não tem saída para o oceano) e o maior corpo de água interior do planeta. Qual é a área total dele, em km²?',
   371000, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Lago Superior, na fronteira entre EUA e Canadá, é o maior dos Grandes Lagos norte-americanos. Qual é a área total dele, em km²?',
   82100, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Lago Tanganica, na África Central, é o segundo lago mais profundo do mundo, atrás só do Baikal. Qual é a área total dele, em km²?',
   32900, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Lagoa dos Patos, no Rio Grande do Sul, é a maior lagoa do Brasil, separada do oceano por uma estreita faixa de areia. Qual é a área total dela, em km²?',
   10140, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Grande Lago do Urso, no Ártico canadense, é o quarto maior lago da América do Norte e fica congelado boa parte do ano. Qual é a área total dele, em km²?',
   31153, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Lago Niassa, na fronteira entre Malawi, Moçambique e Tanzânia, abriga mais espécies de peixes do que qualquer outro lago do mundo. Qual é a área total dele, em km²?',
   29600, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Lago Eyre, no interior desértico da Austrália, é o maior lago do país, mas passa a maior parte do tempo completamente seco. Qual é a área total dele quando cheio, em km²?',
   9500, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 5: Litoral — extensão de costa (km)
  ('O Canadá tem o litoral mais extenso do mundo, recortado por milhares de ilhas árticas e fiordes. Qual é a extensão total do litoral canadense, em km?',
   202080, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Indonésia é formada por mais de 17 mil ilhas, o que dá ao país um dos litorais mais extensos do planeta. Qual é a extensão total do litoral indonésio, em km?',
   54720, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Rússia banha três oceanos diferentes, do Ártico ao Pacífico. Qual é a extensão total do litoral russo, em km?',
   37653, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('As Filipinas são um arquipélago de mais de 7 mil ilhas no Sudeste Asiático. Qual é a extensão total do litoral filipino, em km?',
   36289, 'km', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Japão é formado por quatro ilhas principais e milhares de ilhotas menores. Qual é a extensão total do litoral japonês, em km?',
   29751, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Austrália é o único país do mundo que ocupa um continente inteiro sozinho. Qual é a extensão total do litoral australiano, em km?',
   25760, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Noruega tem um litoral recortado por centenas de fiordes profundos, formados por geleiras na última era do gelo. Qual é a extensão total do litoral norueguês, em km?',
   28953, 'km', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Chile se estende por mais de 4 mil km de norte a sul, sempre colado ao Oceano Pacífico. Qual é a extensão total do litoral chileno, em km?',
   6435, 'km', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Grécia tem mais de 6 mil ilhas e ilhotas, das quais só umas poucas centenas são habitadas. Qual é a extensão total do litoral grego, em km?',
   13676, 'km', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Nova Zelândia é formada por duas ilhas principais bem alongadas, cercadas de água por todos os lados. Qual é a extensão total do litoral neozelandês, em km?',
   15134, 'km', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 6: População — lugares pouco óbvios
  ('Ulan Bator é a capital da Mongólia e considerada a capital nacional mais fria do mundo, com invernos de até -40°C. Quantos habitantes ela tem?',
   1600000, 'habitantes', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Reykjavik é a capital mais setentrional do mundo entre países soberanos, quase tocando o Círculo Polar Ártico. Quantos habitantes ela tem?',
   140000, 'habitantes', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Vaticano é o menor estado soberano do mundo, cercado por completo pela cidade de Roma. Quantos habitantes ele tem?',
   800, 'habitantes', 'geografia', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Nauru é a menor república insular do mundo, no Pacífico, e nem tem uma capital oficialmente definida. Quantos habitantes ela tem?',
   10000, 'habitantes', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Groenlândia é a maior ilha do mundo, mas é um território autônomo dinamarquês quase todo coberto de gelo. Quantos habitantes ela tem?',
   56000, 'habitantes', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Macau é uma região administrativa especial da China, antiga colônia portuguesa hoje famosa pelos cassinos. Quantos habitantes ela tem?',
   700000, 'habitantes', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Tokelau é um território neozelandês formado por três atóis no Pacífico Sul, sem nenhum aeroporto — só se chega de barco. Quantos habitantes ele tem?',
   1500, 'habitantes', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('San Marino é um dos microestados mais antigos do mundo, encravado por inteiro dentro da Itália. Quantos habitantes ele tem?',
   34000, 'habitantes', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('As Ilhas Malvinas, no Atlântico Sul, são administradas pelo Reino Unido e reivindicadas pela Argentina. Quantos habitantes elas têm?',
   3500, 'habitantes', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Andorra é um pequeno país encravado entre a França e a Espanha, em pleno maciço dos Pirineus. Quantos habitantes ela tem?',
   80000, 'habitantes', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 7: Densidade demográfica — habitantes por km²
  ('Mônaco é o segundo menor país do mundo e o mais densamente povoado entre os países soberanos. Qual é a densidade demográfica dele, em habitantes por km²?',
   19000, 'habitantes por km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Singapura é uma cidade-estado insular no Sudeste Asiático, praticamente sem área rural sobrando. Qual é a densidade demográfica dela, em habitantes por km²?',
   8000, 'habitantes por km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Macau, região da China, é uma das áreas mais densamente povoadas do planeta apesar do território minúsculo. Qual é a densidade demográfica dela, em habitantes por km²?',
   21000, 'habitantes por km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Bangladesh é um dos países mais populosos do mundo espremido num território menor que o estado do Amazonas. Qual é a densidade demográfica dele, em habitantes por km²?',
   1265, 'habitantes por km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Malé é a capital das Maldivas, espremida numa ilha minúscula do Oceano Índico, sem quase nenhum espaço livre. Qual é a densidade demográfica dela, em habitantes por km²?',
   65000, 'habitantes por km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Mongólia é um dos maiores países do mundo em área, mas um dos menos povoados de todos. Qual é a densidade demográfica dela, em habitantes por km²?',
   2, 'habitantes por km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Namíbia, no sudoeste da África, tem boa parte do território ocupado pelo deserto do Namibe. Qual é a densidade demográfica dela, em habitantes por km²?',
   3, 'habitantes por km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Austrália ocupa um continente inteiro, mas a maior parte do interior é deserto praticamente vazio. Qual é a densidade demográfica dela, em habitantes por km²?',
   3, 'habitantes por km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Java, na Indonésia, é uma das ilhas mais populosas do mundo, com mais gente vivendo nela do que na Rússia inteira. Qual é a densidade demográfica dela, em habitantes por km²?',
   1100, 'habitantes por km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Suriname, na América do Sul, é coberto quase inteiramente por floresta amazônica intacta. Qual é a densidade demográfica dele, em habitantes por km²?',
   3, 'habitantes por km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 8: Fusos horários — quantidade oficial por país (contando territórios)
  ('A França, contando seus territórios ultramarinos espalhados por todos os oceanos, tem mais fusos horários oficiais do que qualquer outro país do mundo. Quantos fusos horários ela tem?',
   12, 'fusos horários', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Os Estados Unidos, contando territórios como Guam e Samoa Americana, têm fusos que vão do Atlântico ao Pacífico central. Quantos fusos horários eles têm?',
   11, 'fusos horários', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Reino Unido, contando seus territórios ultramarinos espalhados pelo Atlântico e pelo Pacífico, tem fusos bem mais dispersos do que o tamanho da ilha principal sugere. Quantos fusos horários ele tem?',
   9, 'fusos horários', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Canadá se estende por quase toda a largura da América do Norte, do Atlântico ao Pacífico. Quantos fusos horários ele tem?',
   6, 'fusos horários', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Austrália tem fusos horários que incluem uma diferença de meia hora entre alguns de seus estados. Quantos fusos horários ela tem?',
   3, 'fusos horários', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A China tem território largo o bastante para caber cinco fusos horários diferentes, mas o governo impõe um único horário oficial para o país inteiro. Quantos fusos horários oficiais ela tem?',
   1, 'fusos horários', 'geografia', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Brasil já teve até quatro fusos horários oficiais ao mesmo tempo, incluindo o do arquipélago de Fernando de Noronha. Quantos fusos horários ele tem hoje?',
   4, 'fusos horários', 'geografia', 1, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Espanha tem um fuso horário diferente nas Ilhas Canárias em relação ao continente europeu. Quantos fusos horários ela tem?',
   2, 'fusos horários', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Chile tem um fuso horário próprio na Ilha de Páscoa, bem mais a oeste do que o continente. Quantos fusos horários ele tem?',
   3, 'fusos horários', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Kiribati é um pequeno país do Pacífico cujo território foi redesenhado nos mapas nos anos 1990 para não ficar dividido pela linha internacional de data. Quantos fusos horários ele tem?',
   3, 'fusos horários', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 9: Extensão territorial — área de países/estados (km²)
  ('O Cazaquistão é o maior país do mundo sem nenhuma saída para o mar aberto. Qual é a área total dele, em km²?',
   2724900, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Argélia é o maior país da África em área, a maior parte coberta pelo deserto do Saara. Qual é a área total dela, em km²?',
   2381741, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Mongólia é um dos países menos densamente povoados do mundo, apesar de ter um território enorme. Qual é a área total dela, em km²?',
   1564110, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Amazonas é o maior estado brasileiro, maior que muitos países europeus somados. Qual é a área total dele, em km²?',
   1559000, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Groenlândia é a maior ilha do mundo, um território autônomo ligado à Dinamarca. Qual é a área total dela, em km²?',
   2166000, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Argentina é o segundo maior país da América do Sul em área, atrás só do Brasil. Qual é a área total dela, em km²?',
   2780400, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('A Líbia, no norte da África, é quase inteiramente coberta pelo deserto do Saara. Qual é a área total dela, em km²?',
   1759540, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Mato Grosso é um dos maiores estados brasileiros, no coração do país, dividido entre Cerrado e Amazônia. Qual é a área total dele, em km²?',
   903000, 'km²', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Iêmen fica na ponta sul da Península Arábica, na entrada do Mar Vermelho. Qual é a área total dele, em km²?',
   527970, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('O Chade fica no meio do continente africano, sem saída para o mar, com território dividido entre deserto e savana. Qual é a área total dele, em km²?',
   1284000, 'km²', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),

  -- Família 10: Temperatura — recordes e amplitude térmica (°C)
  ('Oymyakon, na Sibéria russa, é considerado o lugar habitado permanentemente mais frio do planeta. Qual foi a menor temperatura já registrada lá, em °C?',
   -67, '°C', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1933, 'pending'),
  ('O Vale da Morte, nos EUA, é um dos lugares mais quentes e secos do planeta, com chuva quase inexistente. Qual foi a maior temperatura já registrada lá, em °C?',
   57, '°C', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1913, 'pending'),
  ('Verkhoyansk, na Sibéria, tem uma das maiores amplitudes térmicas anuais do planeta — de um inverno gelado a um verão surpreendentemente quente. Qual é a diferença entre a maior e a menor temperatura já registradas lá, em °C?',
   105, '°C', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2020, 'pending'),
  ('Cuiabá, no Centro-Oeste brasileiro, é uma das capitais mais quentes do país, com verões que passam fácil dos 40°C. Qual foi a maior temperatura já registrada lá, em °C?',
   42, '°C', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2023, 'pending'),
  ('A estação Vostok, na Antártida, registrou a menor temperatura já medida na superfície da Terra. Qual foi essa temperatura, em °C?',
   -89, '°C', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1983, 'pending'),
  ('A cidade líbia de El Azizia já deteve por décadas o recorde mundial de maior temperatura já registrada, hoje contestado por erro de medição da época. Qual foi essa temperatura, em °C?',
   58, '°C', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1922, 'pending'),
  ('Ushuaia, na Argentina, é considerada a cidade mais austral do mundo, na ponta da Patagônia. Qual foi a menor temperatura já registrada lá, em °C?',
   -22, '°C', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Curitiba é conhecida como uma das capitais brasileiras de clima mais frio, com geadas frequentes no inverno. Qual foi a menor temperatura já registrada lá, em °C?',
   -5, '°C', 'geografia', 2, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending'),
  ('Yakutsk, na Sibéria russa, é considerada a maior cidade construída sobre permafrost e uma das mais frias do planeta. Qual foi a menor temperatura já registrada lá, em °C?',
   -64, '°C', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 1891, 'pending'),
  ('Assuã, no Egito, é uma das cidades habitadas mais quentes e secas do planeta, com chuva praticamente inexistente. Qual foi a maior temperatura já registrada lá, em °C?',
   50, '°C', 'geografia', 3, 'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2024, 'pending');
