-- RASCUNHO NÃO VERIFICADO. Todas as ~100 linhas abaixo foram escritas de memória, sem pesquisa
-- (sem WebSearch/WebFetch) — é geração de volume de candidatos, não curadoria. Todo `answer` é
-- estimativa educada; toda `source_name`/`source_url` é placeholder. status = 'pending' em toda
-- linha; start_round só sorteia status = 'approved', então nada aqui entra em partida real antes
-- de uma sessão futura confirmar cada número com fonte real e decidir aprovar/rejeitar (mesmo
-- processo usado em futebol_25.sql).
--
-- Foco: variar época e região dentro do tema história — antiguidade, idade média, expansão
-- marítima, Américas colonial/independência, Brasil colonial/império/república, África, Ásia — e
-- evitar qualquer fato-base já usado em historia_01.sql/historia_02.sql (Guerra dos Cem Anos,
-- Revolta da Vacina, população de Roma antiga, duração do Império Bizantino, Grande Armée,
-- Grande Fome irlandesa, Corrida do Ouro da Califórnia, Dunquerque, Marcha do Sal de Gandhi).
--
-- Famílias incluídas (cada uma cobre 1 métrica, variando o sujeito/época/região):
--   1.  Duração de guerra ou conflito armado (anos, uma em meses) — 10 conflitos distintos
--   2.  População de cidade antiga ou medieval no seu auge (habitantes) — 10 cidades
--   3.  Tamanho de exército ou frota histórica (soldados ou navios) — 10 forças
--   4.  Distância percorrida numa expedição ou jornada histórica (km) — 10 jornadas
--   5.  Número de vítimas de um evento (mortos) — 10 eventos, catástrofes e revoltas
--   6.  Duração de reinado de monarca (anos) — 10 monarcas
--   7.  Ano de fundação de cidade histórica — 10 cidades
--   8.  Extensão de rota comercial histórica (km) — 10 rotas
--   9.  Quantidade de participantes de revolução, motim ou insurreição (pessoas) — 10 episódios
--   10. Anos entre dois eventos históricos — 10 pares de eventos
insert into public.questions
  (prompt, answer, unit, theme, difficulty, source_name, source_url, as_of_year, status)
values
  -- Família 1: duração de guerra/conflito
  ('A Guerra do Peloponeso opôs Atenas e Esparta pelo domínio da Grécia antiga, com batalhas navais e cercos que se arrastaram por gerações. Quantos anos durou o conflito, entre o primeiro e o último ano?',
   27, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Guerra dos Trinta Anos devastou o Sacro Império Romano-Germânico numa disputa religiosa e política que arrastou quase toda a Europa central. Quantos anos ela durou?',
   30, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Na Segunda Guerra Púnica, Aníbal cruzou os Alpes com seu exército para invadir a Itália e desafiar Roma em seu próprio território. Quantos anos esse conflito durou, do início da invasão até a derrota final de Cartago?',
   17, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Guerra do Paraguai colocou o pequeno país sozinho contra a aliança de Brasil, Argentina e Uruguai, no maior conflito armado já travado na América do Sul. Quantos anos ela durou?',
   6, 'anos', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Na África do Sul, colonos de origem holandesa enfrentaram o Império Britânico por controle das ricas minas de ouro e diamantes na Segunda Guerra dos Bôeres. Quantos anos esse conflito durou?',
   3, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Reconquista foi o longuíssimo processo em que reinos cristãos foram retomando a Península Ibérica do domínio muçulmano, começado logo após a invasão de 711 e só concluído com a queda de Granada. Quantos anos separaram o início da Reconquista e a tomada final de Granada, em 1492?',
   770, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Guerra Cisplatina opôs o Império do Brasil às Províncias Unidas do Rio da Prata pelo controle da região que hoje é o Uruguai. Quantos anos esse conflito durou?',
   3, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Guerra Civil Inglesa colocou apoiadores do rei Carlos I contra o Parlamento, terminando com a execução do monarca e um breve período sem coroa. Quantos anos esse conflito durou, contando desde a primeira batalha até a derrota final dos realistas?',
   9, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Guerra do Contestado foi um conflito camponês e messiânico travado na fronteira entre Santa Catarina e Paraná, reprimido com tropas do Exército brasileiro. Quantos anos esse conflito durou?',
   4, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Guerra Franco-Prussiana terminou com a derrota humilhante da França e a proclamação do Império Alemão no Salão dos Espelhos de Versalhes. Quantos meses esse conflito durou, do início ao armistício?',
   6, 'meses', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 2: população de cidade antiga/histórica
  ('Tenochtitlán, a capital do Império Asteca erguida sobre um lago no Vale do México, impressionou os conquistadores espanhóis pelo tamanho quando chegaram em 1519. Qual era a população estimada da cidade nesse momento, em número de habitantes?',
   200000, 'habitantes', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('No auge do Império Bizantino, sob o imperador Justiniano, Constantinopla era a maior e mais rica cidade do mundo cristão. Qual era a população estimada da cidade no século 6?',
   500000, 'habitantes', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Sob o rei Nabucodonosor II, Babilônia foi reconstruída com seus famosos jardins suspensos e se tornou a maior cidade do mundo conhecido. Qual era sua população estimada nesse período, por volta de 600 a.C.?',
   200000, 'habitantes', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Chang''an, capital da dinastia Tang, era um dos maiores centros urbanos do planeta no auge do comércio pela Rota da Seda. Qual era a população estimada da cidade no século 8?',
   1000000, 'habitantes', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Cusco era a capital sagrada do Império Inca, o centro administrativo de um território que se estendia por boa parte da América do Sul andina. Qual era a população estimada da cidade pouco antes da chegada dos espanhóis?',
   150000, 'habitantes', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Fundada por Alexandre, o Grande, e sede de sua famosa biblioteca, Alexandria foi por séculos um dos maiores centros urbanos do mundo helenístico. Qual era a população estimada da cidade no auge, sob os últimos faraós ptolomaicos?',
   500000, 'habitantes', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Antes de ser arrasada por Roma na Terceira Guerra Púnica, Cartago era uma das maiores cidades comerciais do Mediterrâneo. Qual era sua população estimada no auge do poderio cartaginês?',
   500000, 'habitantes', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Antes de ser dizimada pela Peste Negra, Londres já era o maior centro urbano da Inglaterra medieval. Qual era a população estimada da cidade por volta de 1300?',
   80000, 'habitantes', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Paris era a maior cidade da Europa cristã medieval, sede da monarquia francesa e de uma das primeiras universidades do continente. Qual era sua população estimada no século 14?',
   200000, 'habitantes', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Angkor era a capital do Império Khmer, no Sudeste Asiático, um complexo urbano espalhado por uma área hoje coberta pela selva do Camboja. Qual era a população estimada da área urbana no auge do império, no século 12?',
   750000, 'habitantes', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 3: tamanho de exército/frota histórica
  ('O rei persa Xerxes reuniu uma força descomunal para invadir a Grécia em 480 a.C., tão grande que fontes antigas falam em milhões de homens — número que historiadores modernos consideram bastante exagerado. Qual é a estimativa mais aceita hoje para o tamanho desse exército?',
   200000, 'soldados', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1588, o rei Filipe II da Espanha enviou uma frota para invadir a Inglaterra, batizada pelos próprios espanhóis de Armada Invencível. Quantos navios formavam essa frota?',
   130, 'navios', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1281, Kublai Khan enviou uma imensa frota para invadir o Japão pela segunda vez, destruída por um tufão que os japoneses chamariam de kamikaze. Quantos navios formavam essa frota?',
   4400, 'navios', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('No auge de suas conquistas, Gêngis Khan comandava um dos maiores impérios contíguos da história com um exército relativamente pequeno para o território que controlava. Quantos guerreiros mongóis formavam esse exército no auge?',
   100000, 'soldados', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1683, o Império Otomano cercou Viena numa tentativa de avançar sobre a Europa central, repelida por uma coalizão de forças cristãs. Quantos soldados formavam o exército otomano nesse cerco?',
   150000, 'soldados', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('No desembarque na Normandia, em 6 de junho de 1944, forças aliadas abriram uma nova frente contra a Alemanha nazista na Europa ocidental. Quantos soldados desembarcaram nas praias só no primeiro dia?',
   156000, 'soldados', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O almirante chinês Zheng He liderou expedições marítimas monumentais no início do século 15, décadas antes das grandes navegações europeias. Quantos navios formavam sua maior frota?',
   317, 'navios', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Depois de cruzar os Alpes com seu exército, Aníbal chegou à Itália com boa parte de suas tropas reduzida pelo frio e pelas emboscadas no caminho. Quantos soldados ainda formavam seu exército ao chegar à península?',
   40000, 'soldados', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Batalha de Stalingrado foi um dos maiores confrontos da Segunda Guerra Mundial, com o Exército Vermelho reunindo uma força descomunal para cercar as tropas alemãs. Quantos soldados soviéticos participaram da ofensiva que cercou o 6º Exército alemão?',
   1000000, 'soldados', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Na Batalha de Waterloo, em 1815, Napoleão enfrentou pela última vez uma coalizão europeia, no confronto que encerrou definitivamente sua carreira militar. Quantos soldados formavam o exército francês nessa batalha?',
   72000, 'soldados', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 4: distância percorrida em expedição/jornada histórica
  ('Marco Polo partiu de Veneza rumo à corte do imperador mongol Kublai Khan, numa viagem terrestre que o tornaria um dos exploradores mais famosos da Idade Média. Quantos quilômetros ele percorreu, estima-se, só na ida até a China?',
   24000, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A expedição de Fernão de Magalhães foi a primeira a circunavegar o globo, embora o próprio Magalhães tenha morrido no meio do caminho, nas Filipinas. Quantos quilômetros a viagem completa percorreu, do início ao retorno à Espanha?',
   60000, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A expedição de Raposo Tavares partiu de São Paulo rumo ao interior do continente em busca de indígenas para escravizar e riquezas minerais, avançando bem além das fronteiras que Portugal tinha com a Espanha. Quantos quilômetros essa bandeira percorreu ao todo?',
   10000, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Na Trilha das Lágrimas, o governo dos Estados Unidos forçou povos indígenas, entre eles os Cherokee, a deixar suas terras ancestrais rumo a territórios a oeste do Mississippi, numa marcha que matou milhares pelo caminho. Quantos quilômetros essa marcha forçada percorreu?',
   1200, 'km', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 622 d.C., Maomé deixou Meca rumo a Medina fugindo de perseguição, numa jornada que passaria a marcar o início do calendário islâmico. Quantos quilômetros separam as duas cidades?',
   450, 'km', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Trilha do Oregon foi a principal rota usada por colonos americanos do século 19 para migrar rumo ao Oeste, em carroções puxados por bois. Quantos quilômetros tinha essa trilha, de ponta a ponta?',
   3200, 'km', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A expedição de Lewis e Clark foi enviada pelo governo americano para explorar o território recém-comprado da Louisiana e buscar uma rota até o Oceano Pacífico. Quantos quilômetros a expedição percorreu só na ida?',
   6000, 'km', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Depois de lutar como mercenários gregos numa guerra civil persa que deu errado, o general Xenofonte liderou dez mil soldados numa retirada épica de volta ao território grego. Quantos quilômetros essa retirada percorreu?',
   3500, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Os peregrinos que fundariam a colônia de Plymouth cruzaram o Atlântico a bordo do navio Mayflower, partindo da Inglaterra rumo à costa da atual Massachusetts. Quantos quilômetros essa travessia teve?',
   5300, 'km', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Depois de seu navio ficar preso e afundar no gelo antártico, Ernest Shackleton e uma pequena tripulação navegaram num pequeno bote salva-vidas em busca de ajuda. Quantos quilômetros esse bote, o James Caird, percorreu pelo mar aberto até a Geórgia do Sul?',
   1300, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 5: número de vítimas de evento
  ('A Peste Negra varreu a Europa em meados do século 14, matando uma parcela tão grande da população que mudou para sempre a estrutura social e econômica do continente. Quantas pessoas a peste matou, estima-se, só na Europa?',
   25000000, 'mortos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O terremoto de Lisboa de 1755, seguido de tsunami e incêndio, arrasou a capital portuguesa num dia de grande movimento na cidade. Quantas pessoas morreram nesse desastre?',
   30000, 'mortos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1835, escravizados e libertos de origem africana muçulmana se levantaram nas ruas de Salvador na maior revolta urbana de escravos do Brasil. Quantas pessoas morreram nos confrontos?',
   70, 'mortos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O arraial de Canudos, no sertão da Bahia, reuniu milhares de seguidores do beato Antônio Conselheiro até ser destruído pelo Exército após sucessivas expedições. Quantas pessoas morreram no conflito, entre moradores do arraial e soldados?',
   20000, 'mortos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1919, tropas britânicas abriram fogo contra uma multidão desarmada reunida num jardim fechado na cidade indiana de Amritsar. Quantas pessoas morreram nesse massacre, segundo a contagem oficial britânica da época?',
   379, 'mortos', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1943, sob domínio colonial britânico, a região de Bengala, na Índia, foi atingida por uma fome que se somou aos efeitos da Segunda Guerra Mundial na região. Quantas pessoas morreram nessa fome?',
   3000000, 'mortos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Cabanagem foi uma revolta popular que tomou a província do Grão-Pará, no norte do Brasil, chegando a derrubar o governo provincial por um tempo. Quantas pessoas morreram nesse conflito?',
   30000, 'mortos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1780, o cacique Túpac Amaru II liderou uma grande rebelião indígena contra o domínio colonial espanhol nos Andes peruanos, reprimida com extrema violência. Quantas pessoas morreram nessa rebelião e na repressão que se seguiu?',
   100000, 'mortos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A erupção do vulcão Tambora, na atual Indonésia, em 1815, foi a mais poderosa já registrada pela humanidade, causando fome e frio ao redor do mundo no ano seguinte. Quantas pessoas morreram, direta ou indiretamente, por causa dessa erupção?',
   71000, 'mortos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1556, um terremoto atingiu a província de Shaanxi, na China, numa região onde muita gente morava em casas escavadas em encostas de terra macia. Quantas pessoas morreram nesse terremoto, considerado o mais mortal já registrado na história?',
   830000, 'mortos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 6: duração de reinado de monarca
  ('Luís XIV, o Rei Sol, subiu ao trono francês ainda criança e reinou por mais tempo que qualquer outro monarca europeu bem documentado. Quantos anos durou seu reinado?',
   72, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Rainha Vitória deu nome a uma era inteira da história britânica, marcada pela expansão do Império e pela Revolução Industrial. Quantos anos durou seu reinado?',
   63, 'anos', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('D. Pedro II subiu ao trono do Brasil ainda adolescente e reinou até ser deposto pela proclamação da República. Quantos anos durou seu reinado?',
   58, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O imperador Qianlong governou a China durante boa parte do auge da dinastia Qing, incluindo os anos em que permaneceu no poder como imperador aposentado. Quantos anos durou seu reinado, contando desde a entronização até a morte?',
   60, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Solimão, o Magnífico, levou o Império Otomano ao auge de seu poder territorial e cultural, expandindo suas fronteiras pela Europa, Ásia e África. Quantos anos durou seu reinado?',
   46, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Elizabeth I reinou sobre a Inglaterra numa época de expansão marítima e efervescência cultural, período que ficaria conhecido como a era elisabetana. Quantos anos durou seu reinado?',
   44, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Sobhuza II foi coroado rei da Suazilândia, na África, ainda bebê, e permaneceu no trono por décadas, atravessando o fim do domínio colonial britânico. Quantos anos durou seu reinado, do dia em que se tornou rei até sua morte?',
   82, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O rei Bhumibol Adulyadej da Tailândia subiu ao trono ainda jovem, em meio à Segunda Guerra Mundial, e se tornou uma figura de estabilidade em décadas de turbulência política no país. Quantos anos durou seu reinado?',
   70, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Franz Joseph I governou o Império Austro-Húngaro por tempo suficiente para ver nascer e morrer boa parte da geração que lutaria na Primeira Guerra Mundial, conflito deflagrado ainda em seu reinado. Quantos anos ele reinou?',
   68, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O imperador Hirohito reinou sobre o Japão desde antes da Segunda Guerra Mundial até o fim da Guerra Fria, no reinado mais longo já registrado na história do país. Quantos anos ele reinou?',
   63, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 7: ano de fundação de cidade histórica
  ('A Cidade do Cabo foi fundada pela Companhia Holandesa das Índias Orientais como um posto de reabastecimento para navios a caminho da Ásia, na ponta sul da África. Em que ano ela foi fundada?',
   1652, 'ano', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('São Paulo nasceu como um colégio jesuíta erguido num planalto afastado do litoral, pensado como base para catequizar povos indígenas. Em que ano ele foi fundado?',
   1554, 'ano', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Salvador foi a primeira capital do Brasil colonial, fundada por ordem da coroa portuguesa como sede do governo-geral. Em que ano ela foi fundada?',
   1549, 'ano', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Depois de destruir Tenochtitlán, a capital asteca, os espanhóis ergueram sobre suas ruínas uma nova cidade que se tornaria a capital do vice-reinado da Nova Espanha. Em que ano essa fundação espanhola aconteceu?',
   1521, 'ano', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Timbuktu se tornou um dos maiores centros comerciais e de estudos islâmicos da África Ocidental, ponto de encontro de caravanas que cruzavam o Saara carregando sal e ouro. Em que ano aproximado ela foi fundada, segundo os historiadores?',
   1100, 'ano', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Bagdá foi fundada pelo califa abássida Al-Mansur para ser a nova capital de um império islâmico que se estendia da Península Ibérica à Ásia Central. Em que ano ela foi fundada?',
   762, 'ano', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Kyoto, então chamada Heian-kyo, foi fundada como nova capital imperial do Japão, dando início a um período de mais de quatro séculos que levaria seu nome. Em que ano ela foi fundada?',
   794, 'ano', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Buenos Aires teve uma primeira fundação espanhola destruída por ataques indígenas e precisou ser refundada décadas depois para vingar como cidade. Em que ano aconteceu essa segunda fundação, definitiva?',
   1580, 'ano', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A atual Jacarta nasceu como Batavia, capital das colônias holandesas nas Índias Orientais, erguida sobre um porto conquistado dos sultanatos locais. Em que ano ela foi fundada com esse nome?',
   1619, 'ano', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Potosí nasceu ao pé de uma montanha boliviana riquíssima em prata, e cresceu tão rápido que chegou a rivalizar em população com as maiores cidades europeias da época. Em que ano ela foi fundada?',
   1545, 'ano', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 8: extensão de rota comercial histórica
  ('A Rota da Seda conectava a China ao Mediterrâneo por uma rede de caminhos terrestres, por onde circulavam seda, especiarias e também ideias e doenças. Quantos quilômetros tinha essa rota, de ponta a ponta?',
   6400, 'km', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Rota do Incenso levava resinas aromáticas da Arábia do Sul até os portos do Mediterrâneo, sustentando cidades inteiras que viviam desse comércio. Quantos quilômetros tinha essa rota?',
   2400, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O Caminho de Santiago de Compostela atraía peregrinos medievais de toda a Europa até o suposto túmulo do apóstolo Tiago, no norte da Espanha. Quantos quilômetros tem a rota francesa, a mais tradicional, do ponto de partida até Santiago?',
   800, 'km', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Caravanas de camelos cruzavam o deserto do Saara carregando sal do norte da África e ouro do interior, sustentando impérios como o de Mali. Quantos quilômetros tinha essa travessia entre o norte da África e o Sahel?',
   2000, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Rota do Chá e Cavalos ligava o sudoeste da China ao planalto tibetano, trocando chá chinês por cavalos tibetanos por caminhos de montanha traiçoeiros. Quantos quilômetros tinha essa rota?',
   2250, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Estrada Real do Império Aquemênida ligava as principais cidades da Pérsia antiga, permitindo que mensageiros reais cruzassem o território em tempo recorde. Quantos quilômetros tinha essa estrada?',
   2700, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Via Appia foi uma das primeiras e mais importantes estradas construídas pelos romanos, ligando Roma ao sul da península itálica. Quantos quilômetros tinha essa estrada originalmente?',
   560, 'km', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Grande Estrada Troncal atravessava o subcontinente indiano ligando o Bengala ao Afeganistão, usada por exércitos e caravanas de comerciantes por séculos. Quantos quilômetros tinha essa estrada?',
   2500, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Rota do Âmbar levava âmbar do litoral do mar Báltico até o Mediterrâneo, um comércio de luxo que já existia na Antiguidade. Quantos quilômetros tinha essa rota?',
   2000, 'km', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Durante o tráfico transatlântico de pessoas escravizadas, Luanda, em Angola, era um dos principais portos de embarque com destino ao litoral brasileiro. Quantos quilômetros de oceano separam essas duas cidades?',
   6500, 'km', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 9: quantidade de participantes de revolução/motim/insurreição
  ('Em 14 de julho de 1789, uma multidão de parisienses armados marchou contra a Bastilha, prisão que simbolizava o poder absoluto do rei, num dos episódios que deram início à Revolução Francesa. Quantas pessoas participaram diretamente do assalto à fortaleza?',
   900, 'pessoas', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Espártaco liderou uma revolta de escravos contra Roma que chegou a reunir um verdadeiro exército, vencendo diversas legiões antes de ser finalmente esmagada. Quantas pessoas chegaram a compor esse exército de escravos no auge da revolta?',
   120000, 'pessoas', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Sociedade dos Boxers foi um movimento popular chinês de forte caráter nacionalista e anti-estrangeiro que chegou a cercar bairros diplomáticos em Pequim. Quantas pessoas chegaram a integrar esse movimento no auge da revolta?',
   150000, 'pessoas', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Guerra dos Camponeses Alemães foi a maior revolta popular da Europa antes da Revolução Francesa, com camponeses se levantando contra nobres e a Igreja em diversas regiões germânicas. Quantas pessoas chegaram a participar dessa revolta no seu auge?',
   300000, 'pessoas', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Revolta dos Alfaiates, na Bahia colonial, reuniu artesãos, soldados e escravizados numa conspiração inspirada em ideais da Revolução Francesa. Quantas pessoas foram identificadas como envolvidas na conspiração?',
   40, 'pessoas', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Inconfidência Mineira reuniu um grupo de autoridades, padres e intelectuais de Minas Gerais numa conspiração que planejava a independência da região em relação a Portugal. Quantas pessoas foram identificadas como envolvidas no processo que se seguiu à denúncia?',
   30, 'pessoas', 'historia', 1,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('O Motim de Vellore foi uma das primeiras grandes rebeliões de soldados indianos contra o domínio da Companhia Britânica das Índias Orientais. Quantos soldados indianos participaram desse motim?',
   1500, 'pessoas', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Comuna de Paris foi um governo popular e revolucionário que tomou o controle da capital francesa por alguns meses, defendido por uma milícia armada de trabalhadores. Quantas pessoas chegaram a integrar essa milícia, a Guarda Nacional da Comuna?',
   200000, 'pessoas', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Revolta dos Cipaios foi um levante de soldados indianos a serviço da Companhia Britânica das Índias Orientais que se espalhou rapidamente pelo norte da Índia. Quantos soldados cipaios se rebelaram no início do levante?',
   50000, 'pessoas', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Revolta da Chibata foi um motim de marinheiros da Marinha brasileira contra os castigos físicos a que eram submetidos a bordo dos navios de guerra. Quantos marinheiros participaram desse motim?',
   2000, 'pessoas', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),

  -- Família 10: anos entre dois eventos históricos
  ('Cristóvão Colombo chegou às Américas em 1492, abrindo caminho para a colonização europeia do continente. Quantos anos depois disso os Estados Unidos declarariam sua independência, em 1776?',
   284, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Johannes Gutenberg desenvolveu a prensa de tipos móveis na Alemanha, revolucionando a forma como ideias circulavam pela Europa. Quantos anos depois disso Martinho Lutero afixaria suas teses e daria início à Reforma Protestante?',
   77, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Segundo a tradição, Roma foi fundada em 753 a.C. como um pequeno reino governado por um rei. Quantos anos depois disso os romanos expulsariam seu último rei e fundariam a República?',
   244, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Os portugueses chegaram ao litoral do que viria a ser o Brasil em 1500, dando início à colonização. Quantos anos depois disso o país declararia sua independência de Portugal?',
   322, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Revolução Francesa, em 1789, derrubou a monarquia e inspirou movimentos políticos por toda a Europa. Quantos anos depois disso estourou a Revolução Russa, que derrubaria os czares?',
   128, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1453, os otomanos tomaram Constantinopla e deram fim ao que restava do Império Romano do Oriente. Quantos anos depois disso Cristóvão Colombo chegaria às Américas, financiado pela coroa espanhola?',
   39, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1215, nobres ingleses forçaram o rei João Sem-Terra a assinar a Magna Carta, limitando pela primeira vez o poder absoluto da coroa. Quantos anos depois disso a Revolução Gloriosa consolidaria de vez a supremacia do parlamento inglês sobre o rei?',
   473, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Alexandre, o Grande, morreu em 323 a.C. depois de conquistar um império que ia da Grécia até a Índia. Quantos anos depois disso Otávio Augusto se tornaria o primeiro imperador romano?',
   296, 'anos', 'historia', 3,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('Em 1808, a família real portuguesa fugiu de Napoleão e se instalou no Rio de Janeiro, transferindo a sede do império para a colônia americana. Quantos anos depois disso o Brasil declararia sua independência?',
   14, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending'),
  ('A Peste Negra chegou à Europa em 1347, matando uma parcela enorme da população do continente nos anos seguintes. Quantos anos depois disso Vasco da Gama chegaria à Índia pelo mar, abrindo uma nova rota comercial para os europeus?',
   151, 'anos', 'historia', 2,
   'NÃO VERIFICADO — número candidato, pendente de curadoria', 'pending://sem-fonte-verificada', 2026, 'pending');
